env = Environment(CC='gcc', CCFLAGS='-O0 -gstabs+ -Isrc -Ialloc')
env.Program(target = 'test_all', 
		source = ['test_all.c',
				  'test_binary.c',
				  'test_notation.c',
				  'test_xml.c'],
		LIBS   = ['alloc',
				  'cunit',
				  'llsd',
				  'm'],
		LIBPATH = ['../src/', '../alloc/'])
