env = Environment(CC='gcc', CCFLAGS='-O0 -gstabs+ -Isrc')
env.Program(target = 'test_all', 
		source = ['test_all.c',
				  'test_binary.c',
				  'test_xml.c'],
		LIBS   = ['cunit',
				  'llsd',
				  'm',
				  'expat'],
		LIBPATH = ['../src/'])
