/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 * 
 * This file is not intended to be easily readable and contains a number of 
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG 
 * interface file instead. 
 * ----------------------------------------------------------------------------- */

/* This file should be compiled with 6c/8c.  */
#pragma dynimport _ _ "llsd.so"

#include "runtime.h"
#include "cgocall.h"

#ifdef _64BIT
#define SWIG_PARM_SIZE 8
#else
#define SWIG_PARM_SIZE 4
#endif

#pragma dynimport _wrap_LLSD_UNDEF _wrap_LLSD_UNDEF ""
extern void (*_wrap_LLSD_UNDEF)(void*);
static void (*x_wrap_LLSD_UNDEF)(void*) = _wrap_LLSD_UNDEF;

void
·_swig_getLLSD_UNDEF(struct {
  uint8 x[SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_LLSD_UNDEF, &p);
}



#pragma dynimport _wrap_LLSD_BOOLEAN _wrap_LLSD_BOOLEAN ""
extern void (*_wrap_LLSD_BOOLEAN)(void*);
static void (*x_wrap_LLSD_BOOLEAN)(void*) = _wrap_LLSD_BOOLEAN;

void
·_swig_getLLSD_BOOLEAN(struct {
  uint8 x[SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_LLSD_BOOLEAN, &p);
}



#pragma dynimport _wrap_LLSD_INTEGER _wrap_LLSD_INTEGER ""
extern void (*_wrap_LLSD_INTEGER)(void*);
static void (*x_wrap_LLSD_INTEGER)(void*) = _wrap_LLSD_INTEGER;

void
·_swig_getLLSD_INTEGER(struct {
  uint8 x[SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_LLSD_INTEGER, &p);
}



#pragma dynimport _wrap_LLSD_REAL _wrap_LLSD_REAL ""
extern void (*_wrap_LLSD_REAL)(void*);
static void (*x_wrap_LLSD_REAL)(void*) = _wrap_LLSD_REAL;

void
·_swig_getLLSD_REAL(struct {
  uint8 x[SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_LLSD_REAL, &p);
}



#pragma dynimport _wrap_LLSD_UUID _wrap_LLSD_UUID ""
extern void (*_wrap_LLSD_UUID)(void*);
static void (*x_wrap_LLSD_UUID)(void*) = _wrap_LLSD_UUID;

void
·_swig_getLLSD_UUID(struct {
  uint8 x[SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_LLSD_UUID, &p);
}



#pragma dynimport _wrap_LLSD_STRING _wrap_LLSD_STRING ""
extern void (*_wrap_LLSD_STRING)(void*);
static void (*x_wrap_LLSD_STRING)(void*) = _wrap_LLSD_STRING;

void
·_swig_getLLSD_STRING(struct {
  uint8 x[SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_LLSD_STRING, &p);
}



#pragma dynimport _wrap_LLSD_DATE _wrap_LLSD_DATE ""
extern void (*_wrap_LLSD_DATE)(void*);
static void (*x_wrap_LLSD_DATE)(void*) = _wrap_LLSD_DATE;

void
·_swig_getLLSD_DATE(struct {
  uint8 x[SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_LLSD_DATE, &p);
}



#pragma dynimport _wrap_LLSD_URI _wrap_LLSD_URI ""
extern void (*_wrap_LLSD_URI)(void*);
static void (*x_wrap_LLSD_URI)(void*) = _wrap_LLSD_URI;

void
·_swig_getLLSD_URI(struct {
  uint8 x[SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_LLSD_URI, &p);
}



#pragma dynimport _wrap_LLSD_BINARY _wrap_LLSD_BINARY ""
extern void (*_wrap_LLSD_BINARY)(void*);
static void (*x_wrap_LLSD_BINARY)(void*) = _wrap_LLSD_BINARY;

void
·_swig_getLLSD_BINARY(struct {
  uint8 x[SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_LLSD_BINARY, &p);
}



#pragma dynimport _wrap_LLSD_ARRAY _wrap_LLSD_ARRAY ""
extern void (*_wrap_LLSD_ARRAY)(void*);
static void (*x_wrap_LLSD_ARRAY)(void*) = _wrap_LLSD_ARRAY;

void
·_swig_getLLSD_ARRAY(struct {
  uint8 x[SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_LLSD_ARRAY, &p);
}



#pragma dynimport _wrap_LLSD_MAP _wrap_LLSD_MAP ""
extern void (*_wrap_LLSD_MAP)(void*);
static void (*x_wrap_LLSD_MAP)(void*) = _wrap_LLSD_MAP;

void
·_swig_getLLSD_MAP(struct {
  uint8 x[SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_LLSD_MAP, &p);
}



#pragma dynimport _wrap_LLSD_TYPE_LAST _wrap_LLSD_TYPE_LAST ""
extern void (*_wrap_LLSD_TYPE_LAST)(void*);
static void (*x_wrap_LLSD_TYPE_LAST)(void*) = _wrap_LLSD_TYPE_LAST;

void
·_swig_getLLSD_TYPE_LAST(struct {
  uint8 x[SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_LLSD_TYPE_LAST, &p);
}



#pragma dynimport _wrap_LLSD_TYPE_FIRST _wrap_LLSD_TYPE_FIRST ""
extern void (*_wrap_LLSD_TYPE_FIRST)(void*);
static void (*x_wrap_LLSD_TYPE_FIRST)(void*) = _wrap_LLSD_TYPE_FIRST;

void
·_swig_getLLSD_TYPE_FIRST(struct {
  uint8 x[SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_LLSD_TYPE_FIRST, &p);
}



#pragma dynimport _wrap_LLSD_TYPE_COUNT _wrap_LLSD_TYPE_COUNT ""
extern void (*_wrap_LLSD_TYPE_COUNT)(void*);
static void (*x_wrap_LLSD_TYPE_COUNT)(void*) = _wrap_LLSD_TYPE_COUNT;

void
·_swig_getLLSD_TYPE_COUNT(struct {
  uint8 x[SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_LLSD_TYPE_COUNT, &p);
}



#pragma dynimport _wrap_LLSD_TYPE_INVALID _wrap_LLSD_TYPE_INVALID ""
extern void (*_wrap_LLSD_TYPE_INVALID)(void*);
static void (*x_wrap_LLSD_TYPE_INVALID)(void*) = _wrap_LLSD_TYPE_INVALID;

void
·_swig_getLLSD_TYPE_INVALID(struct {
  uint8 x[SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_LLSD_TYPE_INVALID, &p);
}



#pragma dynimport _wrap_LLSD_KEY _wrap_LLSD_KEY ""
extern void (*_wrap_LLSD_KEY)(void*);
static void (*x_wrap_LLSD_KEY)(void*) = _wrap_LLSD_KEY;

void
·_swig_getLLSD_KEY(struct {
  uint8 x[SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_LLSD_KEY, &p);
}



#pragma dynimport _wrap_LLSD_LLSD _wrap_LLSD_LLSD ""
extern void (*_wrap_LLSD_LLSD)(void*);
static void (*x_wrap_LLSD_LLSD)(void*) = _wrap_LLSD_LLSD;

void
·_swig_getLLSD_LLSD(struct {
  uint8 x[SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_LLSD_LLSD, &p);
}



#pragma dynimport _wrap_llsd_type_strings_get _wrap_llsd_type_strings_get ""
extern void (*_wrap_llsd_type_strings_get)(void*);
static void (*x_wrap_llsd_type_strings_get)(void*) = _wrap_llsd_type_strings_get;

void
·GetLlsd_type_strings(struct {
  uint8 x[SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_llsd_type_strings_get, &p);
}



#pragma dynimport _wrap_LLSD_ENC_XML _wrap_LLSD_ENC_XML ""
extern void (*_wrap_LLSD_ENC_XML)(void*);
static void (*x_wrap_LLSD_ENC_XML)(void*) = _wrap_LLSD_ENC_XML;

void
·_swig_getLLSD_ENC_XML(struct {
  uint8 x[SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_LLSD_ENC_XML, &p);
}



#pragma dynimport _wrap_LLSD_ENC_BINARY _wrap_LLSD_ENC_BINARY ""
extern void (*_wrap_LLSD_ENC_BINARY)(void*);
static void (*x_wrap_LLSD_ENC_BINARY)(void*) = _wrap_LLSD_ENC_BINARY;

void
·_swig_getLLSD_ENC_BINARY(struct {
  uint8 x[SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_LLSD_ENC_BINARY, &p);
}



#pragma dynimport _wrap_LLSD_ENC_NOTATION _wrap_LLSD_ENC_NOTATION ""
extern void (*_wrap_LLSD_ENC_NOTATION)(void*);
static void (*x_wrap_LLSD_ENC_NOTATION)(void*) = _wrap_LLSD_ENC_NOTATION;

void
·_swig_getLLSD_ENC_NOTATION(struct {
  uint8 x[SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_LLSD_ENC_NOTATION, &p);
}



#pragma dynimport _wrap_LLSD_ENC_JSON _wrap_LLSD_ENC_JSON ""
extern void (*_wrap_LLSD_ENC_JSON)(void*);
static void (*x_wrap_LLSD_ENC_JSON)(void*) = _wrap_LLSD_ENC_JSON;

void
·_swig_getLLSD_ENC_JSON(struct {
  uint8 x[SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_LLSD_ENC_JSON, &p);
}



#pragma dynimport _wrap_LLSD_ENC_LAST _wrap_LLSD_ENC_LAST ""
extern void (*_wrap_LLSD_ENC_LAST)(void*);
static void (*x_wrap_LLSD_ENC_LAST)(void*) = _wrap_LLSD_ENC_LAST;

void
·_swig_getLLSD_ENC_LAST(struct {
  uint8 x[SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_LLSD_ENC_LAST, &p);
}



#pragma dynimport _wrap_LLSD_ENC_FIRST _wrap_LLSD_ENC_FIRST ""
extern void (*_wrap_LLSD_ENC_FIRST)(void*);
static void (*x_wrap_LLSD_ENC_FIRST)(void*) = _wrap_LLSD_ENC_FIRST;

void
·_swig_getLLSD_ENC_FIRST(struct {
  uint8 x[SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_LLSD_ENC_FIRST, &p);
}



#pragma dynimport _wrap_LLSD_ENC_COUNT _wrap_LLSD_ENC_COUNT ""
extern void (*_wrap_LLSD_ENC_COUNT)(void*);
static void (*x_wrap_LLSD_ENC_COUNT)(void*) = _wrap_LLSD_ENC_COUNT;

void
·_swig_getLLSD_ENC_COUNT(struct {
  uint8 x[SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_LLSD_ENC_COUNT, &p);
}



#pragma dynimport _wrap_LLSD_NONE _wrap_LLSD_NONE ""
extern void (*_wrap_LLSD_NONE)(void*);
static void (*x_wrap_LLSD_NONE)(void*) = _wrap_LLSD_NONE;

void
·_swig_getLLSD_NONE(struct {
  uint8 x[SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_LLSD_NONE, &p);
}



#pragma dynimport _wrap_LLSD_BASE16 _wrap_LLSD_BASE16 ""
extern void (*_wrap_LLSD_BASE16)(void*);
static void (*x_wrap_LLSD_BASE16)(void*) = _wrap_LLSD_BASE16;

void
·_swig_getLLSD_BASE16(struct {
  uint8 x[SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_LLSD_BASE16, &p);
}



#pragma dynimport _wrap_LLSD_BASE64 _wrap_LLSD_BASE64 ""
extern void (*_wrap_LLSD_BASE64)(void*);
static void (*x_wrap_LLSD_BASE64)(void*) = _wrap_LLSD_BASE64;

void
·_swig_getLLSD_BASE64(struct {
  uint8 x[SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_LLSD_BASE64, &p);
}



#pragma dynimport _wrap_LLSD_BASE85 _wrap_LLSD_BASE85 ""
extern void (*_wrap_LLSD_BASE85)(void*);
static void (*x_wrap_LLSD_BASE85)(void*) = _wrap_LLSD_BASE85;

void
·_swig_getLLSD_BASE85(struct {
  uint8 x[SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_LLSD_BASE85, &p);
}



#pragma dynimport _wrap_LLSD_BIN_ENC_LAST _wrap_LLSD_BIN_ENC_LAST ""
extern void (*_wrap_LLSD_BIN_ENC_LAST)(void*);
static void (*x_wrap_LLSD_BIN_ENC_LAST)(void*) = _wrap_LLSD_BIN_ENC_LAST;

void
·_swig_getLLSD_BIN_ENC_LAST(struct {
  uint8 x[SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_LLSD_BIN_ENC_LAST, &p);
}



#pragma dynimport _wrap_LLSD_BIN_ENC_FIRST _wrap_LLSD_BIN_ENC_FIRST ""
extern void (*_wrap_LLSD_BIN_ENC_FIRST)(void*);
static void (*x_wrap_LLSD_BIN_ENC_FIRST)(void*) = _wrap_LLSD_BIN_ENC_FIRST;

void
·_swig_getLLSD_BIN_ENC_FIRST(struct {
  uint8 x[SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_LLSD_BIN_ENC_FIRST, &p);
}



#pragma dynimport _wrap_LLSD_BIN_ENC_COUNT _wrap_LLSD_BIN_ENC_COUNT ""
extern void (*_wrap_LLSD_BIN_ENC_COUNT)(void*);
static void (*x_wrap_LLSD_BIN_ENC_COUNT)(void*) = _wrap_LLSD_BIN_ENC_COUNT;

void
·_swig_getLLSD_BIN_ENC_COUNT(struct {
  uint8 x[SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_LLSD_BIN_ENC_COUNT, &p);
}



#pragma dynimport _wrap_LLSD_RAW _wrap_LLSD_RAW ""
extern void (*_wrap_LLSD_RAW)(void*);
static void (*x_wrap_LLSD_RAW)(void*) = _wrap_LLSD_RAW;

void
·_swig_getLLSD_RAW(struct {
  uint8 x[SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_LLSD_RAW, &p);
}



#pragma dynimport _wrap_llsd_xml_bin_enc_type_strings_get _wrap_llsd_xml_bin_enc_type_strings_get ""
extern void (*_wrap_llsd_xml_bin_enc_type_strings_get)(void*);
static void (*x_wrap_llsd_xml_bin_enc_type_strings_get)(void*) = _wrap_llsd_xml_bin_enc_type_strings_get;

void
·GetLlsd_xml_bin_enc_type_strings(struct {
  uint8 x[SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_llsd_xml_bin_enc_type_strings_get, &p);
}



#pragma dynimport _wrap_llsd_notation_bin_enc_type_strings_get _wrap_llsd_notation_bin_enc_type_strings_get ""
extern void (*_wrap_llsd_notation_bin_enc_type_strings_get)(void*);
static void (*x_wrap_llsd_notation_bin_enc_type_strings_get)(void*) = _wrap_llsd_notation_bin_enc_type_strings_get;

void
·GetLlsd_notation_bin_enc_type_strings(struct {
  uint8 x[SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_llsd_notation_bin_enc_type_strings_get, &p);
}



#pragma dynimport _wrap_UUID_LEN _wrap_UUID_LEN ""
extern void (*_wrap_UUID_LEN)(void*);
static void (*x_wrap_UUID_LEN)(void*) = _wrap_UUID_LEN;

void
·_swig_getUUID_LEN(struct {
  uint8 x[SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_UUID_LEN, &p);
}



#pragma dynimport _wrap_UUID_STR_LEN _wrap_UUID_STR_LEN ""
extern void (*_wrap_UUID_STR_LEN)(void*);
static void (*x_wrap_UUID_STR_LEN)(void*) = _wrap_UUID_STR_LEN;

void
·_swig_getUUID_STR_LEN(struct {
  uint8 x[SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_UUID_STR_LEN, &p);
}



#pragma dynimport _wrap_DATE_STR_LEN _wrap_DATE_STR_LEN ""
extern void (*_wrap_DATE_STR_LEN)(void*);
static void (*x_wrap_DATE_STR_LEN)(void*) = _wrap_DATE_STR_LEN;

void
·_swig_getDATE_STR_LEN(struct {
  uint8 x[SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_DATE_STR_LEN, &p);
}



#pragma dynimport _wrap_llsd_new _wrap_llsd_new ""
extern void (*_wrap_llsd_new)(void*);
static void (*x_wrap_llsd_new)(void*) = _wrap_llsd_new;

void
·_swig_wrap_llsd_new(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_llsd_new, &p);
}



#pragma dynimport _wrap_llsd_delete _wrap_llsd_delete ""
extern void (*_wrap_llsd_delete)(void*);
static void (*x_wrap_llsd_delete)(void*) = _wrap_llsd_delete;

void
·_swig_wrap_llsd_delete(struct {
  uint8 x[SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_llsd_delete, &p);
}



#pragma dynimport _wrap_llsd_get_type _wrap_llsd_get_type ""
extern void (*_wrap_llsd_get_type)(void*);
static void (*x_wrap_llsd_get_type)(void*) = _wrap_llsd_get_type;

void
·_swig_wrap_llsd_get_type(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_llsd_get_type, &p);
}



#pragma dynimport _wrap_llsd_get_type_string _wrap_llsd_get_type_string ""
extern void (*_wrap_llsd_get_type_string)(void*);
static void (*x_wrap_llsd_get_type_string)(void*) = _wrap_llsd_get_type_string;

void
·_swig_wrap_llsd_get_type_string(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_llsd_get_type_string, &p);
}



#pragma dynimport _wrap_llsd_get_bin_enc_type_string _wrap_llsd_get_bin_enc_type_string ""
extern void (*_wrap_llsd_get_bin_enc_type_string)(void*);
static void (*x_wrap_llsd_get_bin_enc_type_string)(void*) = _wrap_llsd_get_bin_enc_type_string;

void
·_swig_wrap_llsd_get_bin_enc_type_string(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_llsd_get_bin_enc_type_string, &p);
}



#pragma dynimport _wrap_llsd_itr_t_li_set _wrap_llsd_itr_t_li_set ""
extern void (*_wrap_llsd_itr_t_li_set)(void*);
static void (*x_wrap_llsd_itr_t_li_set)(void*) = _wrap_llsd_itr_t_li_set;

void
·_swig_wrap_llsd_itr_t_li_set(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_llsd_itr_t_li_set, &p);
}



#pragma dynimport _wrap_llsd_itr_t_li_get _wrap_llsd_itr_t_li_get ""
extern void (*_wrap_llsd_itr_t_li_get)(void*);
static void (*x_wrap_llsd_itr_t_li_get)(void*) = _wrap_llsd_itr_t_li_get;

void
·_swig_wrap_llsd_itr_t_li_get(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_llsd_itr_t_li_get, &p);
}



#pragma dynimport _wrap_llsd_itr_t_hi_set _wrap_llsd_itr_t_hi_set ""
extern void (*_wrap_llsd_itr_t_hi_set)(void*);
static void (*x_wrap_llsd_itr_t_hi_set)(void*) = _wrap_llsd_itr_t_hi_set;

void
·_swig_wrap_llsd_itr_t_hi_set(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_llsd_itr_t_hi_set, &p);
}



#pragma dynimport _wrap_llsd_itr_t_hi_get _wrap_llsd_itr_t_hi_get ""
extern void (*_wrap_llsd_itr_t_hi_get)(void*);
static void (*x_wrap_llsd_itr_t_hi_get)(void*) = _wrap_llsd_itr_t_hi_get;

void
·_swig_wrap_llsd_itr_t_hi_get(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_llsd_itr_t_hi_get, &p);
}



#pragma dynimport _wrap_new_llsd_itr_t _wrap_new_llsd_itr_t ""
extern void (*_wrap_new_llsd_itr_t)(void*);
static void (*x_wrap_new_llsd_itr_t)(void*) = _wrap_new_llsd_itr_t;

void
·_swig_wrap_new_llsd_itr_t(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_new_llsd_itr_t, &p);
}



#pragma dynimport _wrap_delete_llsd_itr_t _wrap_delete_llsd_itr_t ""
extern void (*_wrap_delete_llsd_itr_t)(void*);
static void (*x_wrap_delete_llsd_itr_t)(void*) = _wrap_delete_llsd_itr_t;

void
·_swig_wrap_delete_llsd_itr_t(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_delete_llsd_itr_t, &p);
}



#pragma dynimport _wrap_llsd_array_append _wrap_llsd_array_append ""
extern void (*_wrap_llsd_array_append)(void*);
static void (*x_wrap_llsd_array_append)(void*) = _wrap_llsd_array_append;

void
·_swig_wrap_llsd_array_append(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_llsd_array_append, &p);
}



#pragma dynimport _wrap_llsd_array_unappend _wrap_llsd_array_unappend ""
extern void (*_wrap_llsd_array_unappend)(void*);
static void (*x_wrap_llsd_array_unappend)(void*) = _wrap_llsd_array_unappend;

void
·_swig_wrap_llsd_array_unappend(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_llsd_array_unappend, &p);
}



#pragma dynimport _wrap_llsd_map_insert _wrap_llsd_map_insert ""
extern void (*_wrap_llsd_map_insert)(void*);
static void (*x_wrap_llsd_map_insert)(void*) = _wrap_llsd_map_insert;

void
·_swig_wrap_llsd_map_insert(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_llsd_map_insert, &p);
}



#pragma dynimport _wrap_llsd_map_remove _wrap_llsd_map_remove ""
extern void (*_wrap_llsd_map_remove)(void*);
static void (*x_wrap_llsd_map_remove)(void*) = _wrap_llsd_map_remove;

void
·_swig_wrap_llsd_map_remove(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_llsd_map_remove, &p);
}



#pragma dynimport _wrap_llsd_itr_begin _wrap_llsd_itr_begin ""
extern void (*_wrap_llsd_itr_begin)(void*);
static void (*x_wrap_llsd_itr_begin)(void*) = _wrap_llsd_itr_begin;

void
·_swig_wrap_llsd_itr_begin(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_llsd_itr_begin, &p);
}



#pragma dynimport _wrap_llsd_itr_end _wrap_llsd_itr_end ""
extern void (*_wrap_llsd_itr_end)(void*);
static void (*x_wrap_llsd_itr_end)(void*) = _wrap_llsd_itr_end;

void
·_swig_wrap_llsd_itr_end(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_llsd_itr_end, &p);
}



#pragma dynimport _wrap_llsd_itr_rbegin _wrap_llsd_itr_rbegin ""
extern void (*_wrap_llsd_itr_rbegin)(void*);
static void (*x_wrap_llsd_itr_rbegin)(void*) = _wrap_llsd_itr_rbegin;

void
·_swig_wrap_llsd_itr_rbegin(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_llsd_itr_rbegin, &p);
}



#pragma dynimport _wrap_llsd_itr_next _wrap_llsd_itr_next ""
extern void (*_wrap_llsd_itr_next)(void*);
static void (*x_wrap_llsd_itr_next)(void*) = _wrap_llsd_itr_next;

void
·_swig_wrap_llsd_itr_next(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_llsd_itr_next, &p);
}



#pragma dynimport _wrap_llsd_itr_rnext _wrap_llsd_itr_rnext ""
extern void (*_wrap_llsd_itr_rnext)(void*);
static void (*x_wrap_llsd_itr_rnext)(void*) = _wrap_llsd_itr_rnext;

void
·_swig_wrap_llsd_itr_rnext(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_llsd_itr_rnext, &p);
}



#pragma dynimport _wrap_llsd_get _wrap_llsd_get ""
extern void (*_wrap_llsd_get)(void*);
static void (*x_wrap_llsd_get)(void*) = _wrap_llsd_get;

void
·_swig_wrap_llsd_get(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_llsd_get, &p);
}



#pragma dynimport _wrap_llsd_map_find_llsd _wrap_llsd_map_find_llsd ""
extern void (*_wrap_llsd_map_find_llsd)(void*);
static void (*x_wrap_llsd_map_find_llsd)(void*) = _wrap_llsd_map_find_llsd;

void
·_swig_wrap_llsd_map_find_llsd(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_llsd_map_find_llsd, &p);
}



#pragma dynimport _wrap_llsd_map_find _wrap_llsd_map_find ""
extern void (*_wrap_llsd_map_find)(void*);
static void (*x_wrap_llsd_map_find)(void*) = _wrap_llsd_map_find;

void
·_swig_wrap_llsd_map_find(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_llsd_map_find, &p);
}



#pragma dynimport _wrap_llsd_as_boolean _wrap_llsd_as_boolean ""
extern void (*_wrap_llsd_as_boolean)(void*);
static void (*x_wrap_llsd_as_boolean)(void*) = _wrap_llsd_as_boolean;

void
·_swig_wrap_llsd_as_boolean(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_llsd_as_boolean, &p);
}



#pragma dynimport _wrap_llsd_as_integer _wrap_llsd_as_integer ""
extern void (*_wrap_llsd_as_integer)(void*);
static void (*x_wrap_llsd_as_integer)(void*) = _wrap_llsd_as_integer;

void
·_swig_wrap_llsd_as_integer(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_llsd_as_integer, &p);
}



#pragma dynimport _wrap_llsd_as_double _wrap_llsd_as_double ""
extern void (*_wrap_llsd_as_double)(void*);
static void (*x_wrap_llsd_as_double)(void*) = _wrap_llsd_as_double;

void
·_swig_wrap_llsd_as_double(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_llsd_as_double, &p);
}



#pragma dynimport _wrap_llsd_as_uuid _wrap_llsd_as_uuid ""
extern void (*_wrap_llsd_as_uuid)(void*);
static void (*x_wrap_llsd_as_uuid)(void*) = _wrap_llsd_as_uuid;

void
·_swig_wrap_llsd_as_uuid(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_llsd_as_uuid, &p);
}



#pragma dynimport _wrap_llsd_as_string _wrap_llsd_as_string ""
extern void (*_wrap_llsd_as_string)(void*);
static void (*x_wrap_llsd_as_string)(void*) = _wrap_llsd_as_string;

void
·_swig_wrap_llsd_as_string(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_llsd_as_string, &p);
}



#pragma dynimport _wrap_llsd_as_binary _wrap_llsd_as_binary ""
extern void (*_wrap_llsd_as_binary)(void*);
static void (*x_wrap_llsd_as_binary)(void*) = _wrap_llsd_as_binary;

void
·_swig_wrap_llsd_as_binary(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_llsd_as_binary, &p);
}



#pragma dynimport _wrap_llsd_equal _wrap_llsd_equal ""
extern void (*_wrap_llsd_equal)(void*);
static void (*x_wrap_llsd_equal)(void*) = _wrap_llsd_equal;

void
·_swig_wrap_llsd_equal(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_llsd_equal, &p);
}



#pragma dynimport _wrap_llsd_get_count _wrap_llsd_get_count ""
extern void (*_wrap_llsd_get_count)(void*);
static void (*x_wrap_llsd_get_count)(void*) = _wrap_llsd_get_count;

void
·_swig_wrap_llsd_get_count(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_llsd_get_count, &p);
}



#pragma dynimport _wrap_llsd_ops_t_undef_fn_set _wrap_llsd_ops_t_undef_fn_set ""
extern void (*_wrap_llsd_ops_t_undef_fn_set)(void*);
static void (*x_wrap_llsd_ops_t_undef_fn_set)(void*) = _wrap_llsd_ops_t_undef_fn_set;

void
·_swig_wrap_llsd_ops_t_undef_fn_set(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_llsd_ops_t_undef_fn_set, &p);
}



#pragma dynimport _wrap_llsd_ops_t_undef_fn_get _wrap_llsd_ops_t_undef_fn_get ""
extern void (*_wrap_llsd_ops_t_undef_fn_get)(void*);
static void (*x_wrap_llsd_ops_t_undef_fn_get)(void*) = _wrap_llsd_ops_t_undef_fn_get;

void
·_swig_wrap_llsd_ops_t_undef_fn_get(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_llsd_ops_t_undef_fn_get, &p);
}



#pragma dynimport _wrap_llsd_ops_t_boolean_fn_set _wrap_llsd_ops_t_boolean_fn_set ""
extern void (*_wrap_llsd_ops_t_boolean_fn_set)(void*);
static void (*x_wrap_llsd_ops_t_boolean_fn_set)(void*) = _wrap_llsd_ops_t_boolean_fn_set;

void
·_swig_wrap_llsd_ops_t_boolean_fn_set(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_llsd_ops_t_boolean_fn_set, &p);
}



#pragma dynimport _wrap_llsd_ops_t_boolean_fn_get _wrap_llsd_ops_t_boolean_fn_get ""
extern void (*_wrap_llsd_ops_t_boolean_fn_get)(void*);
static void (*x_wrap_llsd_ops_t_boolean_fn_get)(void*) = _wrap_llsd_ops_t_boolean_fn_get;

void
·_swig_wrap_llsd_ops_t_boolean_fn_get(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_llsd_ops_t_boolean_fn_get, &p);
}



#pragma dynimport _wrap_llsd_ops_t_integer_fn_set _wrap_llsd_ops_t_integer_fn_set ""
extern void (*_wrap_llsd_ops_t_integer_fn_set)(void*);
static void (*x_wrap_llsd_ops_t_integer_fn_set)(void*) = _wrap_llsd_ops_t_integer_fn_set;

void
·_swig_wrap_llsd_ops_t_integer_fn_set(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_llsd_ops_t_integer_fn_set, &p);
}



#pragma dynimport _wrap_llsd_ops_t_integer_fn_get _wrap_llsd_ops_t_integer_fn_get ""
extern void (*_wrap_llsd_ops_t_integer_fn_get)(void*);
static void (*x_wrap_llsd_ops_t_integer_fn_get)(void*) = _wrap_llsd_ops_t_integer_fn_get;

void
·_swig_wrap_llsd_ops_t_integer_fn_get(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_llsd_ops_t_integer_fn_get, &p);
}



#pragma dynimport _wrap_llsd_ops_t_real_fn_set _wrap_llsd_ops_t_real_fn_set ""
extern void (*_wrap_llsd_ops_t_real_fn_set)(void*);
static void (*x_wrap_llsd_ops_t_real_fn_set)(void*) = _wrap_llsd_ops_t_real_fn_set;

void
·_swig_wrap_llsd_ops_t_real_fn_set(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_llsd_ops_t_real_fn_set, &p);
}



#pragma dynimport _wrap_llsd_ops_t_real_fn_get _wrap_llsd_ops_t_real_fn_get ""
extern void (*_wrap_llsd_ops_t_real_fn_get)(void*);
static void (*x_wrap_llsd_ops_t_real_fn_get)(void*) = _wrap_llsd_ops_t_real_fn_get;

void
·_swig_wrap_llsd_ops_t_real_fn_get(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_llsd_ops_t_real_fn_get, &p);
}



#pragma dynimport _wrap_llsd_ops_t_uuid_fn_set _wrap_llsd_ops_t_uuid_fn_set ""
extern void (*_wrap_llsd_ops_t_uuid_fn_set)(void*);
static void (*x_wrap_llsd_ops_t_uuid_fn_set)(void*) = _wrap_llsd_ops_t_uuid_fn_set;

void
·_swig_wrap_llsd_ops_t_uuid_fn_set(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_llsd_ops_t_uuid_fn_set, &p);
}



#pragma dynimport _wrap_llsd_ops_t_uuid_fn_get _wrap_llsd_ops_t_uuid_fn_get ""
extern void (*_wrap_llsd_ops_t_uuid_fn_get)(void*);
static void (*x_wrap_llsd_ops_t_uuid_fn_get)(void*) = _wrap_llsd_ops_t_uuid_fn_get;

void
·_swig_wrap_llsd_ops_t_uuid_fn_get(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_llsd_ops_t_uuid_fn_get, &p);
}



#pragma dynimport _wrap_llsd_ops_t_string_fn_set _wrap_llsd_ops_t_string_fn_set ""
extern void (*_wrap_llsd_ops_t_string_fn_set)(void*);
static void (*x_wrap_llsd_ops_t_string_fn_set)(void*) = _wrap_llsd_ops_t_string_fn_set;

void
·_swig_wrap_llsd_ops_t_string_fn_set(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_llsd_ops_t_string_fn_set, &p);
}



#pragma dynimport _wrap_llsd_ops_t_string_fn_get _wrap_llsd_ops_t_string_fn_get ""
extern void (*_wrap_llsd_ops_t_string_fn_get)(void*);
static void (*x_wrap_llsd_ops_t_string_fn_get)(void*) = _wrap_llsd_ops_t_string_fn_get;

void
·_swig_wrap_llsd_ops_t_string_fn_get(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_llsd_ops_t_string_fn_get, &p);
}



#pragma dynimport _wrap_llsd_ops_t_date_fn_set _wrap_llsd_ops_t_date_fn_set ""
extern void (*_wrap_llsd_ops_t_date_fn_set)(void*);
static void (*x_wrap_llsd_ops_t_date_fn_set)(void*) = _wrap_llsd_ops_t_date_fn_set;

void
·_swig_wrap_llsd_ops_t_date_fn_set(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_llsd_ops_t_date_fn_set, &p);
}



#pragma dynimport _wrap_llsd_ops_t_date_fn_get _wrap_llsd_ops_t_date_fn_get ""
extern void (*_wrap_llsd_ops_t_date_fn_get)(void*);
static void (*x_wrap_llsd_ops_t_date_fn_get)(void*) = _wrap_llsd_ops_t_date_fn_get;

void
·_swig_wrap_llsd_ops_t_date_fn_get(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_llsd_ops_t_date_fn_get, &p);
}



#pragma dynimport _wrap_llsd_ops_t_uri_fn_set _wrap_llsd_ops_t_uri_fn_set ""
extern void (*_wrap_llsd_ops_t_uri_fn_set)(void*);
static void (*x_wrap_llsd_ops_t_uri_fn_set)(void*) = _wrap_llsd_ops_t_uri_fn_set;

void
·_swig_wrap_llsd_ops_t_uri_fn_set(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_llsd_ops_t_uri_fn_set, &p);
}



#pragma dynimport _wrap_llsd_ops_t_uri_fn_get _wrap_llsd_ops_t_uri_fn_get ""
extern void (*_wrap_llsd_ops_t_uri_fn_get)(void*);
static void (*x_wrap_llsd_ops_t_uri_fn_get)(void*) = _wrap_llsd_ops_t_uri_fn_get;

void
·_swig_wrap_llsd_ops_t_uri_fn_get(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_llsd_ops_t_uri_fn_get, &p);
}



#pragma dynimport _wrap_llsd_ops_t_binary_fn_set _wrap_llsd_ops_t_binary_fn_set ""
extern void (*_wrap_llsd_ops_t_binary_fn_set)(void*);
static void (*x_wrap_llsd_ops_t_binary_fn_set)(void*) = _wrap_llsd_ops_t_binary_fn_set;

void
·_swig_wrap_llsd_ops_t_binary_fn_set(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_llsd_ops_t_binary_fn_set, &p);
}



#pragma dynimport _wrap_llsd_ops_t_binary_fn_get _wrap_llsd_ops_t_binary_fn_get ""
extern void (*_wrap_llsd_ops_t_binary_fn_get)(void*);
static void (*x_wrap_llsd_ops_t_binary_fn_get)(void*) = _wrap_llsd_ops_t_binary_fn_get;

void
·_swig_wrap_llsd_ops_t_binary_fn_get(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_llsd_ops_t_binary_fn_get, &p);
}



#pragma dynimport _wrap_llsd_ops_t_array_begin_fn_set _wrap_llsd_ops_t_array_begin_fn_set ""
extern void (*_wrap_llsd_ops_t_array_begin_fn_set)(void*);
static void (*x_wrap_llsd_ops_t_array_begin_fn_set)(void*) = _wrap_llsd_ops_t_array_begin_fn_set;

void
·_swig_wrap_llsd_ops_t_array_begin_fn_set(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_llsd_ops_t_array_begin_fn_set, &p);
}



#pragma dynimport _wrap_llsd_ops_t_array_begin_fn_get _wrap_llsd_ops_t_array_begin_fn_get ""
extern void (*_wrap_llsd_ops_t_array_begin_fn_get)(void*);
static void (*x_wrap_llsd_ops_t_array_begin_fn_get)(void*) = _wrap_llsd_ops_t_array_begin_fn_get;

void
·_swig_wrap_llsd_ops_t_array_begin_fn_get(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_llsd_ops_t_array_begin_fn_get, &p);
}



#pragma dynimport _wrap_llsd_ops_t_array_value_begin_fn_set _wrap_llsd_ops_t_array_value_begin_fn_set ""
extern void (*_wrap_llsd_ops_t_array_value_begin_fn_set)(void*);
static void (*x_wrap_llsd_ops_t_array_value_begin_fn_set)(void*) = _wrap_llsd_ops_t_array_value_begin_fn_set;

void
·_swig_wrap_llsd_ops_t_array_value_begin_fn_set(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_llsd_ops_t_array_value_begin_fn_set, &p);
}



#pragma dynimport _wrap_llsd_ops_t_array_value_begin_fn_get _wrap_llsd_ops_t_array_value_begin_fn_get ""
extern void (*_wrap_llsd_ops_t_array_value_begin_fn_get)(void*);
static void (*x_wrap_llsd_ops_t_array_value_begin_fn_get)(void*) = _wrap_llsd_ops_t_array_value_begin_fn_get;

void
·_swig_wrap_llsd_ops_t_array_value_begin_fn_get(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_llsd_ops_t_array_value_begin_fn_get, &p);
}



#pragma dynimport _wrap_llsd_ops_t_array_value_end_fn_set _wrap_llsd_ops_t_array_value_end_fn_set ""
extern void (*_wrap_llsd_ops_t_array_value_end_fn_set)(void*);
static void (*x_wrap_llsd_ops_t_array_value_end_fn_set)(void*) = _wrap_llsd_ops_t_array_value_end_fn_set;

void
·_swig_wrap_llsd_ops_t_array_value_end_fn_set(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_llsd_ops_t_array_value_end_fn_set, &p);
}



#pragma dynimport _wrap_llsd_ops_t_array_value_end_fn_get _wrap_llsd_ops_t_array_value_end_fn_get ""
extern void (*_wrap_llsd_ops_t_array_value_end_fn_get)(void*);
static void (*x_wrap_llsd_ops_t_array_value_end_fn_get)(void*) = _wrap_llsd_ops_t_array_value_end_fn_get;

void
·_swig_wrap_llsd_ops_t_array_value_end_fn_get(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_llsd_ops_t_array_value_end_fn_get, &p);
}



#pragma dynimport _wrap_llsd_ops_t_array_end_fn_set _wrap_llsd_ops_t_array_end_fn_set ""
extern void (*_wrap_llsd_ops_t_array_end_fn_set)(void*);
static void (*x_wrap_llsd_ops_t_array_end_fn_set)(void*) = _wrap_llsd_ops_t_array_end_fn_set;

void
·_swig_wrap_llsd_ops_t_array_end_fn_set(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_llsd_ops_t_array_end_fn_set, &p);
}



#pragma dynimport _wrap_llsd_ops_t_array_end_fn_get _wrap_llsd_ops_t_array_end_fn_get ""
extern void (*_wrap_llsd_ops_t_array_end_fn_get)(void*);
static void (*x_wrap_llsd_ops_t_array_end_fn_get)(void*) = _wrap_llsd_ops_t_array_end_fn_get;

void
·_swig_wrap_llsd_ops_t_array_end_fn_get(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_llsd_ops_t_array_end_fn_get, &p);
}



#pragma dynimport _wrap_llsd_ops_t_map_begin_fn_set _wrap_llsd_ops_t_map_begin_fn_set ""
extern void (*_wrap_llsd_ops_t_map_begin_fn_set)(void*);
static void (*x_wrap_llsd_ops_t_map_begin_fn_set)(void*) = _wrap_llsd_ops_t_map_begin_fn_set;

void
·_swig_wrap_llsd_ops_t_map_begin_fn_set(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_llsd_ops_t_map_begin_fn_set, &p);
}



#pragma dynimport _wrap_llsd_ops_t_map_begin_fn_get _wrap_llsd_ops_t_map_begin_fn_get ""
extern void (*_wrap_llsd_ops_t_map_begin_fn_get)(void*);
static void (*x_wrap_llsd_ops_t_map_begin_fn_get)(void*) = _wrap_llsd_ops_t_map_begin_fn_get;

void
·_swig_wrap_llsd_ops_t_map_begin_fn_get(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_llsd_ops_t_map_begin_fn_get, &p);
}



#pragma dynimport _wrap_llsd_ops_t_map_key_begin_fn_set _wrap_llsd_ops_t_map_key_begin_fn_set ""
extern void (*_wrap_llsd_ops_t_map_key_begin_fn_set)(void*);
static void (*x_wrap_llsd_ops_t_map_key_begin_fn_set)(void*) = _wrap_llsd_ops_t_map_key_begin_fn_set;

void
·_swig_wrap_llsd_ops_t_map_key_begin_fn_set(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_llsd_ops_t_map_key_begin_fn_set, &p);
}



#pragma dynimport _wrap_llsd_ops_t_map_key_begin_fn_get _wrap_llsd_ops_t_map_key_begin_fn_get ""
extern void (*_wrap_llsd_ops_t_map_key_begin_fn_get)(void*);
static void (*x_wrap_llsd_ops_t_map_key_begin_fn_get)(void*) = _wrap_llsd_ops_t_map_key_begin_fn_get;

void
·_swig_wrap_llsd_ops_t_map_key_begin_fn_get(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_llsd_ops_t_map_key_begin_fn_get, &p);
}



#pragma dynimport _wrap_llsd_ops_t_map_key_end_fn_set _wrap_llsd_ops_t_map_key_end_fn_set ""
extern void (*_wrap_llsd_ops_t_map_key_end_fn_set)(void*);
static void (*x_wrap_llsd_ops_t_map_key_end_fn_set)(void*) = _wrap_llsd_ops_t_map_key_end_fn_set;

void
·_swig_wrap_llsd_ops_t_map_key_end_fn_set(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_llsd_ops_t_map_key_end_fn_set, &p);
}



#pragma dynimport _wrap_llsd_ops_t_map_key_end_fn_get _wrap_llsd_ops_t_map_key_end_fn_get ""
extern void (*_wrap_llsd_ops_t_map_key_end_fn_get)(void*);
static void (*x_wrap_llsd_ops_t_map_key_end_fn_get)(void*) = _wrap_llsd_ops_t_map_key_end_fn_get;

void
·_swig_wrap_llsd_ops_t_map_key_end_fn_get(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_llsd_ops_t_map_key_end_fn_get, &p);
}



#pragma dynimport _wrap_llsd_ops_t_map_value_begin_fn_set _wrap_llsd_ops_t_map_value_begin_fn_set ""
extern void (*_wrap_llsd_ops_t_map_value_begin_fn_set)(void*);
static void (*x_wrap_llsd_ops_t_map_value_begin_fn_set)(void*) = _wrap_llsd_ops_t_map_value_begin_fn_set;

void
·_swig_wrap_llsd_ops_t_map_value_begin_fn_set(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_llsd_ops_t_map_value_begin_fn_set, &p);
}



#pragma dynimport _wrap_llsd_ops_t_map_value_begin_fn_get _wrap_llsd_ops_t_map_value_begin_fn_get ""
extern void (*_wrap_llsd_ops_t_map_value_begin_fn_get)(void*);
static void (*x_wrap_llsd_ops_t_map_value_begin_fn_get)(void*) = _wrap_llsd_ops_t_map_value_begin_fn_get;

void
·_swig_wrap_llsd_ops_t_map_value_begin_fn_get(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_llsd_ops_t_map_value_begin_fn_get, &p);
}



#pragma dynimport _wrap_llsd_ops_t_map_value_end_fn_set _wrap_llsd_ops_t_map_value_end_fn_set ""
extern void (*_wrap_llsd_ops_t_map_value_end_fn_set)(void*);
static void (*x_wrap_llsd_ops_t_map_value_end_fn_set)(void*) = _wrap_llsd_ops_t_map_value_end_fn_set;

void
·_swig_wrap_llsd_ops_t_map_value_end_fn_set(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_llsd_ops_t_map_value_end_fn_set, &p);
}



#pragma dynimport _wrap_llsd_ops_t_map_value_end_fn_get _wrap_llsd_ops_t_map_value_end_fn_get ""
extern void (*_wrap_llsd_ops_t_map_value_end_fn_get)(void*);
static void (*x_wrap_llsd_ops_t_map_value_end_fn_get)(void*) = _wrap_llsd_ops_t_map_value_end_fn_get;

void
·_swig_wrap_llsd_ops_t_map_value_end_fn_get(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_llsd_ops_t_map_value_end_fn_get, &p);
}



#pragma dynimport _wrap_llsd_ops_t_map_end_fn_set _wrap_llsd_ops_t_map_end_fn_set ""
extern void (*_wrap_llsd_ops_t_map_end_fn_set)(void*);
static void (*x_wrap_llsd_ops_t_map_end_fn_set)(void*) = _wrap_llsd_ops_t_map_end_fn_set;

void
·_swig_wrap_llsd_ops_t_map_end_fn_set(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_llsd_ops_t_map_end_fn_set, &p);
}



#pragma dynimport _wrap_llsd_ops_t_map_end_fn_get _wrap_llsd_ops_t_map_end_fn_get ""
extern void (*_wrap_llsd_ops_t_map_end_fn_get)(void*);
static void (*x_wrap_llsd_ops_t_map_end_fn_get)(void*) = _wrap_llsd_ops_t_map_end_fn_get;

void
·_swig_wrap_llsd_ops_t_map_end_fn_get(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_llsd_ops_t_map_end_fn_get, &p);
}



#pragma dynimport _wrap_new_llsd_ops_t _wrap_new_llsd_ops_t ""
extern void (*_wrap_new_llsd_ops_t)(void*);
static void (*x_wrap_new_llsd_ops_t)(void*) = _wrap_new_llsd_ops_t;

void
·_swig_wrap_new_llsd_ops_t(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_new_llsd_ops_t, &p);
}



#pragma dynimport _wrap_delete_llsd_ops_t _wrap_delete_llsd_ops_t ""
extern void (*_wrap_delete_llsd_ops_t)(void*);
static void (*x_wrap_delete_llsd_ops_t)(void*) = _wrap_delete_llsd_ops_t;

void
·_swig_wrap_delete_llsd_ops_t(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_delete_llsd_ops_t, &p);
}



#pragma dynimport _wrap_TOP_LEVEL _wrap_TOP_LEVEL ""
extern void (*_wrap_TOP_LEVEL)(void*);
static void (*x_wrap_TOP_LEVEL)(void*) = _wrap_TOP_LEVEL;

void
·_swig_getTOP_LEVEL(struct {
  uint8 x[SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_TOP_LEVEL, &p);
}



#pragma dynimport _wrap_ARRAY_BEGIN _wrap_ARRAY_BEGIN ""
extern void (*_wrap_ARRAY_BEGIN)(void*);
static void (*x_wrap_ARRAY_BEGIN)(void*) = _wrap_ARRAY_BEGIN;

void
·_swig_getARRAY_BEGIN(struct {
  uint8 x[SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_ARRAY_BEGIN, &p);
}



#pragma dynimport _wrap_ARRAY_VALUE_BEGIN _wrap_ARRAY_VALUE_BEGIN ""
extern void (*_wrap_ARRAY_VALUE_BEGIN)(void*);
static void (*x_wrap_ARRAY_VALUE_BEGIN)(void*) = _wrap_ARRAY_VALUE_BEGIN;

void
·_swig_getARRAY_VALUE_BEGIN(struct {
  uint8 x[SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_ARRAY_VALUE_BEGIN, &p);
}



#pragma dynimport _wrap_ARRAY_VALUE _wrap_ARRAY_VALUE ""
extern void (*_wrap_ARRAY_VALUE)(void*);
static void (*x_wrap_ARRAY_VALUE)(void*) = _wrap_ARRAY_VALUE;

void
·_swig_getARRAY_VALUE(struct {
  uint8 x[SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_ARRAY_VALUE, &p);
}



#pragma dynimport _wrap_ARRAY_VALUE_END _wrap_ARRAY_VALUE_END ""
extern void (*_wrap_ARRAY_VALUE_END)(void*);
static void (*x_wrap_ARRAY_VALUE_END)(void*) = _wrap_ARRAY_VALUE_END;

void
·_swig_getARRAY_VALUE_END(struct {
  uint8 x[SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_ARRAY_VALUE_END, &p);
}



#pragma dynimport _wrap_ARRAY_END _wrap_ARRAY_END ""
extern void (*_wrap_ARRAY_END)(void*);
static void (*x_wrap_ARRAY_END)(void*) = _wrap_ARRAY_END;

void
·_swig_getARRAY_END(struct {
  uint8 x[SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_ARRAY_END, &p);
}



#pragma dynimport _wrap_MAP_BEGIN _wrap_MAP_BEGIN ""
extern void (*_wrap_MAP_BEGIN)(void*);
static void (*x_wrap_MAP_BEGIN)(void*) = _wrap_MAP_BEGIN;

void
·_swig_getMAP_BEGIN(struct {
  uint8 x[SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_MAP_BEGIN, &p);
}



#pragma dynimport _wrap_MAP_KEY_BEGIN _wrap_MAP_KEY_BEGIN ""
extern void (*_wrap_MAP_KEY_BEGIN)(void*);
static void (*x_wrap_MAP_KEY_BEGIN)(void*) = _wrap_MAP_KEY_BEGIN;

void
·_swig_getMAP_KEY_BEGIN(struct {
  uint8 x[SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_MAP_KEY_BEGIN, &p);
}



#pragma dynimport _wrap_MAP_KEY _wrap_MAP_KEY ""
extern void (*_wrap_MAP_KEY)(void*);
static void (*x_wrap_MAP_KEY)(void*) = _wrap_MAP_KEY;

void
·_swig_getMAP_KEY(struct {
  uint8 x[SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_MAP_KEY, &p);
}



#pragma dynimport _wrap_MAP_KEY_END _wrap_MAP_KEY_END ""
extern void (*_wrap_MAP_KEY_END)(void*);
static void (*x_wrap_MAP_KEY_END)(void*) = _wrap_MAP_KEY_END;

void
·_swig_getMAP_KEY_END(struct {
  uint8 x[SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_MAP_KEY_END, &p);
}



#pragma dynimport _wrap_MAP_VALUE_BEGIN _wrap_MAP_VALUE_BEGIN ""
extern void (*_wrap_MAP_VALUE_BEGIN)(void*);
static void (*x_wrap_MAP_VALUE_BEGIN)(void*) = _wrap_MAP_VALUE_BEGIN;

void
·_swig_getMAP_VALUE_BEGIN(struct {
  uint8 x[SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_MAP_VALUE_BEGIN, &p);
}



#pragma dynimport _wrap_MAP_VALUE _wrap_MAP_VALUE ""
extern void (*_wrap_MAP_VALUE)(void*);
static void (*x_wrap_MAP_VALUE)(void*) = _wrap_MAP_VALUE;

void
·_swig_getMAP_VALUE(struct {
  uint8 x[SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_MAP_VALUE, &p);
}



#pragma dynimport _wrap_MAP_VALUE_END _wrap_MAP_VALUE_END ""
extern void (*_wrap_MAP_VALUE_END)(void*);
static void (*x_wrap_MAP_VALUE_END)(void*) = _wrap_MAP_VALUE_END;

void
·_swig_getMAP_VALUE_END(struct {
  uint8 x[SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_MAP_VALUE_END, &p);
}



#pragma dynimport _wrap_MAP_END _wrap_MAP_END ""
extern void (*_wrap_MAP_END)(void*);
static void (*x_wrap_MAP_END)(void*) = _wrap_MAP_END;

void
·_swig_getMAP_END(struct {
  uint8 x[SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_MAP_END, &p);
}



#pragma dynimport _wrap_llsd_serialize_to_file _wrap_llsd_serialize_to_file ""
extern void (*_wrap_llsd_serialize_to_file)(void*);
static void (*x_wrap_llsd_serialize_to_file)(void*) = _wrap_llsd_serialize_to_file;

void
·_swig_wrap_llsd_serialize_to_file(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_llsd_serialize_to_file, &p);
}



#pragma dynimport _wrap_llsd_parse_from_file _wrap_llsd_parse_from_file ""
extern void (*_wrap_llsd_parse_from_file)(void*);
static void (*x_wrap_llsd_parse_from_file)(void*) = _wrap_llsd_parse_from_file;

void
·_swig_wrap_llsd_parse_from_file(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_llsd_parse_from_file, &p);
}



