/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 * 
 * This file is not intended to be easily readable and contains a number of 
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG 
 * interface file instead. 
 * ----------------------------------------------------------------------------- */
/* -----------------------------------------------------------------------------
 *  This section contains generic SWIG labels for method/variable
 *  declarations/attributes, and other compiler dependent labels.
 * ----------------------------------------------------------------------------- */

/* template workaround for compilers that cannot correctly implement the C++ standard */
#ifndef SWIGTEMPLATEDISAMBIGUATOR
# if defined(__SUNPRO_CC) && (__SUNPRO_CC <= 0x560)
#  define SWIGTEMPLATEDISAMBIGUATOR template
# elif defined(__HP_aCC)
/* Needed even with `aCC -AA' when `aCC -V' reports HP ANSI C++ B3910B A.03.55 */
/* If we find a maximum version that requires this, the test would be __HP_aCC <= 35500 for A.03.55 */
#  define SWIGTEMPLATEDISAMBIGUATOR template
# else
#  define SWIGTEMPLATEDISAMBIGUATOR
# endif
#endif

/* inline attribute */
#ifndef SWIGINLINE
# if defined(__cplusplus) || (defined(__GNUC__) && !defined(__STRICT_ANSI__))
#   define SWIGINLINE inline
# else
#   define SWIGINLINE
# endif
#endif

/* attribute recognised by some compilers to avoid 'unused' warnings */
#ifndef SWIGUNUSED
# if defined(__GNUC__)
#   if !(defined(__cplusplus)) || (__GNUC__ > 3 || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4))
#     define SWIGUNUSED __attribute__ ((__unused__)) 
#   else
#     define SWIGUNUSED
#   endif
# elif defined(__ICC)
#   define SWIGUNUSED __attribute__ ((__unused__)) 
# else
#   define SWIGUNUSED 
# endif
#endif

#ifndef SWIG_MSC_UNSUPPRESS_4505
# if defined(_MSC_VER)
#   pragma warning(disable : 4505) /* unreferenced local function has been removed */
# endif 
#endif

#ifndef SWIGUNUSEDPARM
# ifdef __cplusplus
#   define SWIGUNUSEDPARM(p)
# else
#   define SWIGUNUSEDPARM(p) p SWIGUNUSED 
# endif
#endif

/* internal SWIG method */
#ifndef SWIGINTERN
# define SWIGINTERN static SWIGUNUSED
#endif

/* internal inline SWIG method */
#ifndef SWIGINTERNINLINE
# define SWIGINTERNINLINE SWIGINTERN SWIGINLINE
#endif

/* exporting methods */
#if (__GNUC__ >= 4) || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4)
#  ifndef GCC_HASCLASSVISIBILITY
#    define GCC_HASCLASSVISIBILITY
#  endif
#endif

#ifndef SWIGEXPORT
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   if defined(STATIC_LINKED)
#     define SWIGEXPORT
#   else
#     define SWIGEXPORT __declspec(dllexport)
#   endif
# else
#   if defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
#     define SWIGEXPORT __attribute__ ((visibility("default")))
#   else
#     define SWIGEXPORT
#   endif
# endif
#endif

/* calling conventions for Windows */
#ifndef SWIGSTDCALL
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   define SWIGSTDCALL __stdcall
# else
#   define SWIGSTDCALL
# endif 
#endif

/* Deal with Microsoft's attempt at deprecating C standard runtime functions */
#if !defined(SWIG_NO_CRT_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_CRT_SECURE_NO_DEPRECATE)
# define _CRT_SECURE_NO_DEPRECATE
#endif

/* Deal with Microsoft's attempt at deprecating methods in the standard C++ library */
#if !defined(SWIG_NO_SCL_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_SCL_SECURE_NO_DEPRECATE)
# define _SCL_SECURE_NO_DEPRECATE
#endif



#include <stdio.h>
#include <stdlib.h>
#include <string.h>

typedef struct { char *p; int n; } _gostring_;
typedef struct { void* array; unsigned int len; unsigned int cap; } _goslice_;




#define swiggo_size_assert_eq(x, y, name) typedef char name[(x-y)*(x-y)*-2+1];
#define swiggo_size_assert(t, n) swiggo_size_assert_eq(sizeof(t), n, swiggo_sizeof_##t##_is_not_##n)

swiggo_size_assert(char, 1)
swiggo_size_assert(short, 2)
swiggo_size_assert(int, 4)
typedef long long swiggo_long_long;
swiggo_size_assert(swiggo_long_long, 8)
swiggo_size_assert(float, 4)
swiggo_size_assert(double, 8)

#ifdef __cplusplus
extern "C" {
#endif
extern void crosscall2(void (*fn)(void *, int), void *, int);
extern void _cgo_allocate(void *, int);
extern void _cgo_panic(void *, int);
#ifdef __cplusplus
}
#endif

static void *_swig_goallocate(size_t len) {
  struct {
    size_t len;
    void *ret;
  } a;
  a.len = len;
  crosscall2(_cgo_allocate, &a, (int) sizeof a);
  return a.ret;
}

static void _swig_gopanic(const char *p) {
  struct {
    const char *p;
  } a;
  a.p = p;
  crosscall2(_cgo_panic, &a, (int) sizeof a);
}




static _gostring_ _swig_makegostring(const char *p, size_t l) {
  _gostring_ ret;
  ret.p = (char*)_swig_goallocate(l + 1);
  memcpy(ret.p, p, l);
  ret.n = l;
  return ret;
}

#define SWIG_contract_assert(expr, msg) \
  if (!(expr)) { _swig_gopanic(msg); } else


#include <errno.h>
#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>
#include <string.h>
#include <time.h>
#include <sys/time.h>
#include <cutil/debug.h>
#include <cutil/macros.h>
#include <cllsd/llsd.h>
#include <cllsd/llsd_serializer.h>
#include <cllsd/llsd_parser.h>

#ifdef __cplusplus
extern "C" {
#endif

void
_wrap_LLSD_UNDEF(void *swig_v)
{
  enum llsd_type_e result;
  
  struct swigargs {
    long : 0;
    enum llsd_type_e result;
  } *swig_a = (struct swigargs *) swig_v;
  
  
  result = LLSD_UNDEF;
  
  swig_a->result = result; 
}


void
_wrap_LLSD_BOOLEAN(void *swig_v)
{
  enum llsd_type_e result;
  
  struct swigargs {
    long : 0;
    enum llsd_type_e result;
  } *swig_a = (struct swigargs *) swig_v;
  
  
  result = LLSD_BOOLEAN;
  
  swig_a->result = result; 
}


void
_wrap_LLSD_INTEGER(void *swig_v)
{
  enum llsd_type_e result;
  
  struct swigargs {
    long : 0;
    enum llsd_type_e result;
  } *swig_a = (struct swigargs *) swig_v;
  
  
  result = LLSD_INTEGER;
  
  swig_a->result = result; 
}


void
_wrap_LLSD_REAL(void *swig_v)
{
  enum llsd_type_e result;
  
  struct swigargs {
    long : 0;
    enum llsd_type_e result;
  } *swig_a = (struct swigargs *) swig_v;
  
  
  result = LLSD_REAL;
  
  swig_a->result = result; 
}


void
_wrap_LLSD_UUID(void *swig_v)
{
  enum llsd_type_e result;
  
  struct swigargs {
    long : 0;
    enum llsd_type_e result;
  } *swig_a = (struct swigargs *) swig_v;
  
  
  result = LLSD_UUID;
  
  swig_a->result = result; 
}


void
_wrap_LLSD_STRING(void *swig_v)
{
  enum llsd_type_e result;
  
  struct swigargs {
    long : 0;
    enum llsd_type_e result;
  } *swig_a = (struct swigargs *) swig_v;
  
  
  result = LLSD_STRING;
  
  swig_a->result = result; 
}


void
_wrap_LLSD_DATE(void *swig_v)
{
  enum llsd_type_e result;
  
  struct swigargs {
    long : 0;
    enum llsd_type_e result;
  } *swig_a = (struct swigargs *) swig_v;
  
  
  result = LLSD_DATE;
  
  swig_a->result = result; 
}


void
_wrap_LLSD_URI(void *swig_v)
{
  enum llsd_type_e result;
  
  struct swigargs {
    long : 0;
    enum llsd_type_e result;
  } *swig_a = (struct swigargs *) swig_v;
  
  
  result = LLSD_URI;
  
  swig_a->result = result; 
}


void
_wrap_LLSD_BINARY(void *swig_v)
{
  enum llsd_type_e result;
  
  struct swigargs {
    long : 0;
    enum llsd_type_e result;
  } *swig_a = (struct swigargs *) swig_v;
  
  
  result = LLSD_BINARY;
  
  swig_a->result = result; 
}


void
_wrap_LLSD_ARRAY(void *swig_v)
{
  enum llsd_type_e result;
  
  struct swigargs {
    long : 0;
    enum llsd_type_e result;
  } *swig_a = (struct swigargs *) swig_v;
  
  
  result = LLSD_ARRAY;
  
  swig_a->result = result; 
}


void
_wrap_LLSD_MAP(void *swig_v)
{
  enum llsd_type_e result;
  
  struct swigargs {
    long : 0;
    enum llsd_type_e result;
  } *swig_a = (struct swigargs *) swig_v;
  
  
  result = LLSD_MAP;
  
  swig_a->result = result; 
}


void
_wrap_LLSD_TYPE_LAST(void *swig_v)
{
  enum llsd_type_e result;
  
  struct swigargs {
    long : 0;
    enum llsd_type_e result;
  } *swig_a = (struct swigargs *) swig_v;
  
  
  result = LLSD_TYPE_LAST;
  
  swig_a->result = result; 
}


void
_wrap_LLSD_TYPE_FIRST(void *swig_v)
{
  enum llsd_type_e result;
  
  struct swigargs {
    long : 0;
    enum llsd_type_e result;
  } *swig_a = (struct swigargs *) swig_v;
  
  
  result = LLSD_TYPE_FIRST;
  
  swig_a->result = result; 
}


void
_wrap_LLSD_TYPE_COUNT(void *swig_v)
{
  enum llsd_type_e result;
  
  struct swigargs {
    long : 0;
    enum llsd_type_e result;
  } *swig_a = (struct swigargs *) swig_v;
  
  
  result = LLSD_TYPE_COUNT;
  
  swig_a->result = result; 
}


void
_wrap_LLSD_TYPE_INVALID(void *swig_v)
{
  enum llsd_type_e result;
  
  struct swigargs {
    long : 0;
    enum llsd_type_e result;
  } *swig_a = (struct swigargs *) swig_v;
  
  
  result = LLSD_TYPE_INVALID;
  
  swig_a->result = result; 
}


void
_wrap_LLSD_KEY(void *swig_v)
{
  enum llsd_type_e result;
  
  struct swigargs {
    long : 0;
    enum llsd_type_e result;
  } *swig_a = (struct swigargs *) swig_v;
  
  
  result = LLSD_KEY;
  
  swig_a->result = result; 
}


void
_wrap_LLSD_LLSD(void *swig_v)
{
  enum llsd_type_e result;
  
  struct swigargs {
    long : 0;
    enum llsd_type_e result;
  } *swig_a = (struct swigargs *) swig_v;
  
  
  result = LLSD_LLSD;
  
  swig_a->result = result; 
}


void
_wrap_llsd_type_strings_get(void *swig_v)
{
  int8_t **result = 0 ;
  
  struct swigargs {
    long : 0;
    int8_t **result;
  } *swig_a = (struct swigargs *) swig_v;
  
  
  result = (int8_t **)(int8_t **)llsd_type_strings;
  *(int8_t ***)&swig_a->result = result; 
}


void
_wrap_LLSD_ENC_XML(void *swig_v)
{
  enum llsd_serializer_s result;
  
  struct swigargs {
    long : 0;
    enum llsd_serializer_s result;
  } *swig_a = (struct swigargs *) swig_v;
  
  
  result = LLSD_ENC_XML;
  
  swig_a->result = result; 
}


void
_wrap_LLSD_ENC_BINARY(void *swig_v)
{
  enum llsd_serializer_s result;
  
  struct swigargs {
    long : 0;
    enum llsd_serializer_s result;
  } *swig_a = (struct swigargs *) swig_v;
  
  
  result = LLSD_ENC_BINARY;
  
  swig_a->result = result; 
}


void
_wrap_LLSD_ENC_NOTATION(void *swig_v)
{
  enum llsd_serializer_s result;
  
  struct swigargs {
    long : 0;
    enum llsd_serializer_s result;
  } *swig_a = (struct swigargs *) swig_v;
  
  
  result = LLSD_ENC_NOTATION;
  
  swig_a->result = result; 
}


void
_wrap_LLSD_ENC_JSON(void *swig_v)
{
  enum llsd_serializer_s result;
  
  struct swigargs {
    long : 0;
    enum llsd_serializer_s result;
  } *swig_a = (struct swigargs *) swig_v;
  
  
  result = LLSD_ENC_JSON;
  
  swig_a->result = result; 
}


void
_wrap_LLSD_ENC_LAST(void *swig_v)
{
  enum llsd_serializer_s result;
  
  struct swigargs {
    long : 0;
    enum llsd_serializer_s result;
  } *swig_a = (struct swigargs *) swig_v;
  
  
  result = LLSD_ENC_LAST;
  
  swig_a->result = result; 
}


void
_wrap_LLSD_ENC_FIRST(void *swig_v)
{
  enum llsd_serializer_s result;
  
  struct swigargs {
    long : 0;
    enum llsd_serializer_s result;
  } *swig_a = (struct swigargs *) swig_v;
  
  
  result = LLSD_ENC_FIRST;
  
  swig_a->result = result; 
}


void
_wrap_LLSD_ENC_COUNT(void *swig_v)
{
  enum llsd_serializer_s result;
  
  struct swigargs {
    long : 0;
    enum llsd_serializer_s result;
  } *swig_a = (struct swigargs *) swig_v;
  
  
  result = LLSD_ENC_COUNT;
  
  swig_a->result = result; 
}


void
_wrap_LLSD_NONE(void *swig_v)
{
  enum llsd_bin_enc_s result;
  
  struct swigargs {
    long : 0;
    enum llsd_bin_enc_s result;
  } *swig_a = (struct swigargs *) swig_v;
  
  
  result = LLSD_NONE;
  
  swig_a->result = result; 
}


void
_wrap_LLSD_BASE16(void *swig_v)
{
  enum llsd_bin_enc_s result;
  
  struct swigargs {
    long : 0;
    enum llsd_bin_enc_s result;
  } *swig_a = (struct swigargs *) swig_v;
  
  
  result = LLSD_BASE16;
  
  swig_a->result = result; 
}


void
_wrap_LLSD_BASE64(void *swig_v)
{
  enum llsd_bin_enc_s result;
  
  struct swigargs {
    long : 0;
    enum llsd_bin_enc_s result;
  } *swig_a = (struct swigargs *) swig_v;
  
  
  result = LLSD_BASE64;
  
  swig_a->result = result; 
}


void
_wrap_LLSD_BASE85(void *swig_v)
{
  enum llsd_bin_enc_s result;
  
  struct swigargs {
    long : 0;
    enum llsd_bin_enc_s result;
  } *swig_a = (struct swigargs *) swig_v;
  
  
  result = LLSD_BASE85;
  
  swig_a->result = result; 
}


void
_wrap_LLSD_BIN_ENC_LAST(void *swig_v)
{
  enum llsd_bin_enc_s result;
  
  struct swigargs {
    long : 0;
    enum llsd_bin_enc_s result;
  } *swig_a = (struct swigargs *) swig_v;
  
  
  result = LLSD_BIN_ENC_LAST;
  
  swig_a->result = result; 
}


void
_wrap_LLSD_BIN_ENC_FIRST(void *swig_v)
{
  enum llsd_bin_enc_s result;
  
  struct swigargs {
    long : 0;
    enum llsd_bin_enc_s result;
  } *swig_a = (struct swigargs *) swig_v;
  
  
  result = LLSD_BIN_ENC_FIRST;
  
  swig_a->result = result; 
}


void
_wrap_LLSD_BIN_ENC_COUNT(void *swig_v)
{
  enum llsd_bin_enc_s result;
  
  struct swigargs {
    long : 0;
    enum llsd_bin_enc_s result;
  } *swig_a = (struct swigargs *) swig_v;
  
  
  result = LLSD_BIN_ENC_COUNT;
  
  swig_a->result = result; 
}


void
_wrap_LLSD_RAW(void *swig_v)
{
  enum llsd_bin_enc_s result;
  
  struct swigargs {
    long : 0;
    enum llsd_bin_enc_s result;
  } *swig_a = (struct swigargs *) swig_v;
  
  
  result = LLSD_RAW;
  
  swig_a->result = result; 
}


void
_wrap_llsd_xml_bin_enc_type_strings_get(void *swig_v)
{
  int8_t **result = 0 ;
  
  struct swigargs {
    long : 0;
    int8_t **result;
  } *swig_a = (struct swigargs *) swig_v;
  
  
  result = (int8_t **)(int8_t **)llsd_xml_bin_enc_type_strings;
  *(int8_t ***)&swig_a->result = result; 
}


void
_wrap_llsd_notation_bin_enc_type_strings_get(void *swig_v)
{
  int8_t **result = 0 ;
  
  struct swigargs {
    long : 0;
    int8_t **result;
  } *swig_a = (struct swigargs *) swig_v;
  
  
  result = (int8_t **)(int8_t **)llsd_notation_bin_enc_type_strings;
  *(int8_t ***)&swig_a->result = result; 
}


void
_wrap_UUID_LEN(void *swig_v)
{
  int result;
  
  struct swigargs {
    long : 0;
    int result;
  } *swig_a = (struct swigargs *) swig_v;
  
  
  result = (16);
  
  swig_a->result = result; 
}


void
_wrap_UUID_STR_LEN(void *swig_v)
{
  int result;
  
  struct swigargs {
    long : 0;
    int result;
  } *swig_a = (struct swigargs *) swig_v;
  
  
  result = (36);
  
  swig_a->result = result; 
}


void
_wrap_DATE_STR_LEN(void *swig_v)
{
  int result;
  
  struct swigargs {
    long : 0;
    int result;
  } *swig_a = (struct swigargs *) swig_v;
  
  
  result = (24);
  
  swig_a->result = result; 
}


void
_wrap_llsd_new(void *swig_v)
{
  llsd_type_t arg1 ;
  void *arg2 = 0 ;
  llsd_t *result = 0 ;
  
  struct swigargs {
    llsd_type_t arg1;
    long : 0;
    struct llsd_s *result;
  } *swig_a = (struct swigargs *) swig_v;
  
  arg1 = (llsd_type_t)swig_a->arg1; 
  
  result = (llsd_t *)llsd_new(arg1,arg2);
  *(llsd_t **)&swig_a->result = result; 
}


void
_wrap_llsd_delete(void *swig_v)
{
  void *arg1 = (void *) 0 ;
  
  struct swigargs {
    void *arg1;
  } *swig_a = (struct swigargs *) swig_v;
  
  arg1 = *(void **)&swig_a->arg1; 
  
  llsd_delete(arg1);
  
}


void
_wrap_llsd_get_type(void *swig_v)
{
  llsd_t *arg1 = (llsd_t *) 0 ;
  llsd_type_t result;
  
  struct swigargs {
    struct llsd_s *arg1;
    long : 0;
    llsd_type_t result;
  } *swig_a = (struct swigargs *) swig_v;
  
  arg1 = *(llsd_t **)&swig_a->arg1; 
  
  result = (llsd_type_t)llsd_get_type(arg1);
  swig_a->result = result; 
}


void
_wrap_llsd_get_type_string(void *swig_v)
{
  llsd_type_t arg1 ;
  int8_t *result = 0 ;
  
  struct swigargs {
    llsd_type_t arg1;
    long : 0;
    int8_t *result;
  } *swig_a = (struct swigargs *) swig_v;
  
  arg1 = (llsd_type_t)swig_a->arg1; 
  
  result = (int8_t *)llsd_get_type_string(arg1);
  *(int8_t **)&swig_a->result = result; 
}


void
_wrap_llsd_get_bin_enc_type_string(void *swig_v)
{
  llsd_bin_enc_t arg1 ;
  llsd_serializer_t arg2 ;
  int8_t *result = 0 ;
  
  struct swigargs {
    llsd_bin_enc_t arg1;
    llsd_serializer_t arg2;
    long : 0;
    int8_t *result;
  } *swig_a = (struct swigargs *) swig_v;
  
  arg1 = (llsd_bin_enc_t)swig_a->arg1; 
  arg2 = (llsd_serializer_t)swig_a->arg2; 
  
  result = (int8_t *)llsd_get_bin_enc_type_string(arg1,arg2);
  *(int8_t **)&swig_a->result = result; 
}


void
_wrap_llsd_itr_t_li_set(void *swig_v)
{
  llsd_itr_t *arg1 = (llsd_itr_t *) 0 ;
  list_itr_t arg2 ;
  list_itr_t *argp2 ;
  
  struct swigargs {
    struct llsd_itr_s *arg1;
    list_itr_t *arg2;
  } *swig_a = (struct swigargs *) swig_v;
  
  arg1 = *(llsd_itr_t **)&swig_a->arg1; 
  
  argp2 = (list_itr_t *)swig_a->arg2;
  if (argp2 == NULL) {
    _swig_gopanic("Attempt to dereference null list_itr_t");
  }
  arg2 = (list_itr_t)*argp2;
  
  
  if (arg1) (arg1)->li = arg2;
  
}


void
_wrap_llsd_itr_t_li_get(void *swig_v)
{
  llsd_itr_t *arg1 = (llsd_itr_t *) 0 ;
  list_itr_t result;
  
  struct swigargs {
    struct llsd_itr_s *arg1;
    long : 0;
    list_itr_t *result;
  } *swig_a = (struct swigargs *) swig_v;
  
  arg1 = *(llsd_itr_t **)&swig_a->arg1; 
  
  result =  ((arg1)->li);
  {
    list_itr_t * resultptr = (list_itr_t *)malloc(sizeof(list_itr_t));
    memmove(resultptr, &result, sizeof(list_itr_t));
    *(list_itr_t **)&swig_a->result = resultptr;
  }
}


void
_wrap_llsd_itr_t_hi_set(void *swig_v)
{
  llsd_itr_t *arg1 = (llsd_itr_t *) 0 ;
  ht_itr_t arg2 ;
  ht_itr_t *argp2 ;
  
  struct swigargs {
    struct llsd_itr_s *arg1;
    ht_itr_t *arg2;
  } *swig_a = (struct swigargs *) swig_v;
  
  arg1 = *(llsd_itr_t **)&swig_a->arg1; 
  
  argp2 = (ht_itr_t *)swig_a->arg2;
  if (argp2 == NULL) {
    _swig_gopanic("Attempt to dereference null ht_itr_t");
  }
  arg2 = (ht_itr_t)*argp2;
  
  
  if (arg1) (arg1)->hi = arg2;
  
}


void
_wrap_llsd_itr_t_hi_get(void *swig_v)
{
  llsd_itr_t *arg1 = (llsd_itr_t *) 0 ;
  ht_itr_t result;
  
  struct swigargs {
    struct llsd_itr_s *arg1;
    long : 0;
    ht_itr_t *result;
  } *swig_a = (struct swigargs *) swig_v;
  
  arg1 = *(llsd_itr_t **)&swig_a->arg1; 
  
  result =  ((arg1)->hi);
  {
    ht_itr_t * resultptr = (ht_itr_t *)malloc(sizeof(ht_itr_t));
    memmove(resultptr, &result, sizeof(ht_itr_t));
    *(ht_itr_t **)&swig_a->result = resultptr;
  }
}


void
_wrap_new_llsd_itr_t(void *swig_v)
{
  llsd_itr_t *result = 0 ;
  
  struct swigargs {
    long : 0;
    struct llsd_itr_s *result;
  } *swig_a = (struct swigargs *) swig_v;
  
  
  result = (llsd_itr_t *)calloc(1, sizeof(llsd_itr_t));
  *(llsd_itr_t **)&swig_a->result = result; 
}


void
_wrap_delete_llsd_itr_t(void *swig_v)
{
  llsd_itr_t *arg1 = (llsd_itr_t *) 0 ;
  
  struct swigargs {
    struct llsd_itr_s *arg1;
  } *swig_a = (struct swigargs *) swig_v;
  
  arg1 = *(llsd_itr_t **)&swig_a->arg1; 
  
  free((char *) arg1);
  
}


void
_wrap_llsd_array_append(void *swig_v)
{
  llsd_t *arg1 = (llsd_t *) 0 ;
  llsd_t *arg2 = (llsd_t *) 0 ;
  int result;
  
  struct swigargs {
    struct llsd_s *arg1;
    struct llsd_s *arg2;
    long : 0;
    int result;
  } *swig_a = (struct swigargs *) swig_v;
  
  arg1 = *(llsd_t **)&swig_a->arg1; 
  arg2 = *(llsd_t **)&swig_a->arg2; 
  
  result = (int)llsd_array_append(arg1,arg2);
  swig_a->result = result; 
}


void
_wrap_llsd_array_unappend(void *swig_v)
{
  llsd_t *arg1 = (llsd_t *) 0 ;
  int result;
  
  struct swigargs {
    struct llsd_s *arg1;
    long : 0;
    int result;
  } *swig_a = (struct swigargs *) swig_v;
  
  arg1 = *(llsd_t **)&swig_a->arg1; 
  
  result = (int)llsd_array_unappend(arg1);
  swig_a->result = result; 
}


void
_wrap_llsd_map_insert(void *swig_v)
{
  llsd_t *arg1 = (llsd_t *) 0 ;
  llsd_t *arg2 = (llsd_t *) 0 ;
  llsd_t *arg3 = (llsd_t *) 0 ;
  int result;
  
  struct swigargs {
    struct llsd_s *arg1;
    struct llsd_s *arg2;
    struct llsd_s *arg3;
    long : 0;
    int result;
  } *swig_a = (struct swigargs *) swig_v;
  
  arg1 = *(llsd_t **)&swig_a->arg1; 
  arg2 = *(llsd_t **)&swig_a->arg2; 
  arg3 = *(llsd_t **)&swig_a->arg3; 
  
  result = (int)llsd_map_insert(arg1,arg2,arg3);
  swig_a->result = result; 
}


void
_wrap_llsd_map_remove(void *swig_v)
{
  llsd_t *arg1 = (llsd_t *) 0 ;
  llsd_t *arg2 = (llsd_t *) 0 ;
  int result;
  
  struct swigargs {
    struct llsd_s *arg1;
    struct llsd_s *arg2;
    long : 0;
    int result;
  } *swig_a = (struct swigargs *) swig_v;
  
  arg1 = *(llsd_t **)&swig_a->arg1; 
  arg2 = *(llsd_t **)&swig_a->arg2; 
  
  result = (int)llsd_map_remove(arg1,arg2);
  swig_a->result = result; 
}


void
_wrap_llsd_itr_begin(void *swig_v)
{
  llsd_t *arg1 = (llsd_t *) 0 ;
  llsd_itr_t result;
  
  struct swigargs {
    struct llsd_s *arg1;
    long : 0;
    struct llsd_itr_s *result;
  } *swig_a = (struct swigargs *) swig_v;
  
  arg1 = *(llsd_t **)&swig_a->arg1; 
  
  result = llsd_itr_begin(arg1);
  {
    llsd_itr_t * resultptr = (llsd_itr_t *)malloc(sizeof(llsd_itr_t));
    memmove(resultptr, &result, sizeof(llsd_itr_t));
    *(llsd_itr_t **)&swig_a->result = resultptr;
  }
}


void
_wrap_llsd_itr_end(void *swig_v)
{
  llsd_t *arg1 = (llsd_t *) 0 ;
  llsd_itr_t result;
  
  struct swigargs {
    struct llsd_s *arg1;
    long : 0;
    struct llsd_itr_s *result;
  } *swig_a = (struct swigargs *) swig_v;
  
  arg1 = *(llsd_t **)&swig_a->arg1; 
  
  result = llsd_itr_end(arg1);
  {
    llsd_itr_t * resultptr = (llsd_itr_t *)malloc(sizeof(llsd_itr_t));
    memmove(resultptr, &result, sizeof(llsd_itr_t));
    *(llsd_itr_t **)&swig_a->result = resultptr;
  }
}


void
_wrap_llsd_itr_rbegin(void *swig_v)
{
  llsd_t *arg1 = (llsd_t *) 0 ;
  llsd_itr_t result;
  
  struct swigargs {
    struct llsd_s *arg1;
    long : 0;
    struct llsd_itr_s *result;
  } *swig_a = (struct swigargs *) swig_v;
  
  arg1 = *(llsd_t **)&swig_a->arg1; 
  
  result = llsd_itr_rbegin(arg1);
  {
    llsd_itr_t * resultptr = (llsd_itr_t *)malloc(sizeof(llsd_itr_t));
    memmove(resultptr, &result, sizeof(llsd_itr_t));
    *(llsd_itr_t **)&swig_a->result = resultptr;
  }
}


void
_wrap_llsd_itr_next(void *swig_v)
{
  llsd_t *arg1 = (llsd_t *) 0 ;
  llsd_itr_t arg2 ;
  llsd_itr_t *argp2 ;
  llsd_itr_t result;
  
  struct swigargs {
    struct llsd_s *arg1;
    struct llsd_itr_s *arg2;
    long : 0;
    struct llsd_itr_s *result;
  } *swig_a = (struct swigargs *) swig_v;
  
  arg1 = *(llsd_t **)&swig_a->arg1; 
  
  argp2 = (llsd_itr_t *)swig_a->arg2;
  if (argp2 == NULL) {
    _swig_gopanic("Attempt to dereference null llsd_itr_t");
  }
  arg2 = (llsd_itr_t)*argp2;
  
  
  result = llsd_itr_next(arg1,arg2);
  {
    llsd_itr_t * resultptr = (llsd_itr_t *)malloc(sizeof(llsd_itr_t));
    memmove(resultptr, &result, sizeof(llsd_itr_t));
    *(llsd_itr_t **)&swig_a->result = resultptr;
  }
}


void
_wrap_llsd_itr_rnext(void *swig_v)
{
  llsd_t *arg1 = (llsd_t *) 0 ;
  llsd_itr_t arg2 ;
  llsd_itr_t *argp2 ;
  llsd_itr_t result;
  
  struct swigargs {
    struct llsd_s *arg1;
    struct llsd_itr_s *arg2;
    long : 0;
    struct llsd_itr_s *result;
  } *swig_a = (struct swigargs *) swig_v;
  
  arg1 = *(llsd_t **)&swig_a->arg1; 
  
  argp2 = (llsd_itr_t *)swig_a->arg2;
  if (argp2 == NULL) {
    _swig_gopanic("Attempt to dereference null llsd_itr_t");
  }
  arg2 = (llsd_itr_t)*argp2;
  
  
  result = llsd_itr_rnext(arg1,arg2);
  {
    llsd_itr_t * resultptr = (llsd_itr_t *)malloc(sizeof(llsd_itr_t));
    memmove(resultptr, &result, sizeof(llsd_itr_t));
    *(llsd_itr_t **)&swig_a->result = resultptr;
  }
}


void
_wrap_llsd_get(void *swig_v)
{
  llsd_t *arg1 = (llsd_t *) 0 ;
  llsd_itr_t arg2 ;
  llsd_t **arg3 = (llsd_t **) 0 ;
  llsd_t **arg4 = (llsd_t **) 0 ;
  llsd_itr_t *argp2 ;
  int result;
  
  struct swigargs {
    struct llsd_s *arg1;
    struct llsd_itr_s *arg2;
    struct llsd_s **arg3;
    struct llsd_s **arg4;
    long : 0;
    int result;
  } *swig_a = (struct swigargs *) swig_v;
  
  arg1 = *(llsd_t **)&swig_a->arg1; 
  
  argp2 = (llsd_itr_t *)swig_a->arg2;
  if (argp2 == NULL) {
    _swig_gopanic("Attempt to dereference null llsd_itr_t");
  }
  arg2 = (llsd_itr_t)*argp2;
  
  arg3 = *(llsd_t ***)&swig_a->arg3; 
  arg4 = *(llsd_t ***)&swig_a->arg4; 
  
  result = (int)llsd_get(arg1,arg2,arg3,arg4);
  swig_a->result = result; 
}


void
_wrap_llsd_map_find_llsd(void *swig_v)
{
  llsd_t *arg1 = (llsd_t *) 0 ;
  llsd_t *arg2 = (llsd_t *) 0 ;
  llsd_t *result = 0 ;
  
  struct swigargs {
    struct llsd_s *arg1;
    struct llsd_s *arg2;
    long : 0;
    struct llsd_s *result;
  } *swig_a = (struct swigargs *) swig_v;
  
  arg1 = *(llsd_t **)&swig_a->arg1; 
  arg2 = *(llsd_t **)&swig_a->arg2; 
  
  result = (llsd_t *)llsd_map_find_llsd(arg1,arg2);
  *(llsd_t **)&swig_a->result = result; 
}


void
_wrap_llsd_map_find(void *swig_v)
{
  llsd_t *arg1 = (llsd_t *) 0 ;
  uint8_t *arg2 = (uint8_t *) (uint8_t *)0 ;
  llsd_t *result = 0 ;
  
  struct swigargs {
    struct llsd_s *arg1;
    uint8_t *arg2;
    long : 0;
    struct llsd_s *result;
  } *swig_a = (struct swigargs *) swig_v;
  
  arg1 = *(llsd_t **)&swig_a->arg1; 
  arg2 = *(uint8_t **)&swig_a->arg2; 
  
  result = (llsd_t *)llsd_map_find(arg1,(uint8_t const *)arg2);
  *(llsd_t **)&swig_a->result = result; 
}


void
_wrap_llsd_as_boolean(void *swig_v)
{
  llsd_t *arg1 = (llsd_t *) 0 ;
  int *arg2 = (int *) 0 ;
  int result;
  
  struct swigargs {
    struct llsd_s *arg1;
    int *arg2;
    long : 0;
    int result;
  } *swig_a = (struct swigargs *) swig_v;
  
  arg1 = *(llsd_t **)&swig_a->arg1; 
  arg2 = *(int **)&swig_a->arg2; 
  
  result = (int)llsd_as_boolean(arg1,arg2);
  swig_a->result = result; 
}


void
_wrap_llsd_as_integer(void *swig_v)
{
  llsd_t *arg1 = (llsd_t *) 0 ;
  int32_t *arg2 = (int32_t *) 0 ;
  int result;
  
  struct swigargs {
    struct llsd_s *arg1;
    int32_t *arg2;
    long : 0;
    int result;
  } *swig_a = (struct swigargs *) swig_v;
  
  arg1 = *(llsd_t **)&swig_a->arg1; 
  arg2 = *(int32_t **)&swig_a->arg2; 
  
  result = (int)llsd_as_integer(arg1,arg2);
  swig_a->result = result; 
}


void
_wrap_llsd_as_double(void *swig_v)
{
  llsd_t *arg1 = (llsd_t *) 0 ;
  double *arg2 = (double *) 0 ;
  int result;
  
  struct swigargs {
    struct llsd_s *arg1;
    double *arg2;
    long : 0;
    int result;
  } *swig_a = (struct swigargs *) swig_v;
  
  arg1 = *(llsd_t **)&swig_a->arg1; 
  arg2 = *(double **)&swig_a->arg2; 
  
  result = (int)llsd_as_double(arg1,arg2);
  swig_a->result = result; 
}


void
_wrap_llsd_as_uuid(void *swig_v)
{
  llsd_t *arg1 = (llsd_t *) 0 ;
  uint8_t *arg2 ;
  int result;
  
  struct swigargs {
    struct llsd_s *arg1;
    uint8_t (*arg2)[(16)];
    long : 0;
    int result;
  } *swig_a = (struct swigargs *) swig_v;
  
  arg1 = *(llsd_t **)&swig_a->arg1; 
  arg2 = *(uint8_t **)&swig_a->arg2; 
  
  result = (int)llsd_as_uuid(arg1,arg2);
  swig_a->result = result; 
}


void
_wrap_llsd_as_string(void *swig_v)
{
  llsd_t *arg1 = (llsd_t *) 0 ;
  uint8_t **arg2 = (uint8_t **) 0 ;
  int result;
  
  struct swigargs {
    struct llsd_s *arg1;
    uint8_t **arg2;
    long : 0;
    int result;
  } *swig_a = (struct swigargs *) swig_v;
  
  arg1 = *(llsd_t **)&swig_a->arg1; 
  arg2 = *(uint8_t ***)&swig_a->arg2; 
  
  result = (int)llsd_as_string(arg1,arg2);
  swig_a->result = result; 
}


void
_wrap_llsd_as_binary(void *swig_v)
{
  llsd_t *arg1 = (llsd_t *) 0 ;
  uint8_t **arg2 = (uint8_t **) 0 ;
  uint32_t *arg3 = (uint32_t *) 0 ;
  int result;
  
  struct swigargs {
    struct llsd_s *arg1;
    uint8_t **arg2;
    uint32_t *arg3;
    long : 0;
    int result;
  } *swig_a = (struct swigargs *) swig_v;
  
  arg1 = *(llsd_t **)&swig_a->arg1; 
  arg2 = *(uint8_t ***)&swig_a->arg2; 
  arg3 = *(uint32_t **)&swig_a->arg3; 
  
  result = (int)llsd_as_binary(arg1,arg2,arg3);
  swig_a->result = result; 
}


void
_wrap_llsd_equal(void *swig_v)
{
  llsd_t *arg1 = (llsd_t *) 0 ;
  llsd_t *arg2 = (llsd_t *) 0 ;
  int result;
  
  struct swigargs {
    struct llsd_s *arg1;
    struct llsd_s *arg2;
    long : 0;
    int result;
  } *swig_a = (struct swigargs *) swig_v;
  
  arg1 = *(llsd_t **)&swig_a->arg1; 
  arg2 = *(llsd_t **)&swig_a->arg2; 
  
  result = (int)llsd_equal(arg1,arg2);
  swig_a->result = result; 
}


void
_wrap_llsd_get_count(void *swig_v)
{
  llsd_t *arg1 = (llsd_t *) 0 ;
  int result;
  
  struct swigargs {
    struct llsd_s *arg1;
    long : 0;
    int result;
  } *swig_a = (struct swigargs *) swig_v;
  
  arg1 = *(llsd_t **)&swig_a->arg1; 
  
  result = (int)llsd_get_count(arg1);
  swig_a->result = result; 
}


void
_wrap_llsd_ops_t_undef_fn_set(void *swig_v)
{
  llsd_ops_t *arg1 = (llsd_ops_t *) 0 ;
  int (*arg2)(void *const) = (int (*)(void *const)) 0 ;
  
  struct swigargs {
    struct llsd_ops_s *arg1;
    void *arg2;
  } *swig_a = (struct swigargs *) swig_v;
  
  arg1 = *(llsd_ops_t **)&swig_a->arg1; 
  arg2 = *(int (**)(void *const))&swig_a->arg2; 
  
  if (arg1) (arg1)->undef_fn = arg2;
  
}


void
_wrap_llsd_ops_t_undef_fn_get(void *swig_v)
{
  llsd_ops_t *arg1 = (llsd_ops_t *) 0 ;
  int (*result)(void *const) = 0 ;
  
  struct swigargs {
    struct llsd_ops_s *arg1;
    long : 0;
    void *result;
  } *swig_a = (struct swigargs *) swig_v;
  
  arg1 = *(llsd_ops_t **)&swig_a->arg1; 
  
  result = (int (*)(void *const)) ((arg1)->undef_fn);
  *(int (**)(void *const))&swig_a->result = result; 
}


void
_wrap_llsd_ops_t_boolean_fn_set(void *swig_v)
{
  llsd_ops_t *arg1 = (llsd_ops_t *) 0 ;
  int (*arg2)(int const,void *const) = (int (*)(int const,void *const)) 0 ;
  
  struct swigargs {
    struct llsd_ops_s *arg1;
    void *arg2;
  } *swig_a = (struct swigargs *) swig_v;
  
  arg1 = *(llsd_ops_t **)&swig_a->arg1; 
  arg2 = *(int (**)(int const,void *const))&swig_a->arg2; 
  
  if (arg1) (arg1)->boolean_fn = arg2;
  
}


void
_wrap_llsd_ops_t_boolean_fn_get(void *swig_v)
{
  llsd_ops_t *arg1 = (llsd_ops_t *) 0 ;
  int (*result)(int const,void *const) = 0 ;
  
  struct swigargs {
    struct llsd_ops_s *arg1;
    long : 0;
    void *result;
  } *swig_a = (struct swigargs *) swig_v;
  
  arg1 = *(llsd_ops_t **)&swig_a->arg1; 
  
  result = (int (*)(int const,void *const)) ((arg1)->boolean_fn);
  *(int (**)(int const,void *const))&swig_a->result = result; 
}


void
_wrap_llsd_ops_t_integer_fn_set(void *swig_v)
{
  llsd_ops_t *arg1 = (llsd_ops_t *) 0 ;
  int (*arg2)(int32_t const,void *const) = (int (*)(int32_t const,void *const)) 0 ;
  
  struct swigargs {
    struct llsd_ops_s *arg1;
    void *arg2;
  } *swig_a = (struct swigargs *) swig_v;
  
  arg1 = *(llsd_ops_t **)&swig_a->arg1; 
  arg2 = *(int (**)(int32_t const,void *const))&swig_a->arg2; 
  
  if (arg1) (arg1)->integer_fn = arg2;
  
}


void
_wrap_llsd_ops_t_integer_fn_get(void *swig_v)
{
  llsd_ops_t *arg1 = (llsd_ops_t *) 0 ;
  int (*result)(int32_t const,void *const) = 0 ;
  
  struct swigargs {
    struct llsd_ops_s *arg1;
    long : 0;
    void *result;
  } *swig_a = (struct swigargs *) swig_v;
  
  arg1 = *(llsd_ops_t **)&swig_a->arg1; 
  
  result = (int (*)(int32_t const,void *const)) ((arg1)->integer_fn);
  *(int (**)(int32_t const,void *const))&swig_a->result = result; 
}


void
_wrap_llsd_ops_t_real_fn_set(void *swig_v)
{
  llsd_ops_t *arg1 = (llsd_ops_t *) 0 ;
  int (*arg2)(double const,void *const) = (int (*)(double const,void *const)) 0 ;
  
  struct swigargs {
    struct llsd_ops_s *arg1;
    void *arg2;
  } *swig_a = (struct swigargs *) swig_v;
  
  arg1 = *(llsd_ops_t **)&swig_a->arg1; 
  arg2 = *(int (**)(double const,void *const))&swig_a->arg2; 
  
  if (arg1) (arg1)->real_fn = arg2;
  
}


void
_wrap_llsd_ops_t_real_fn_get(void *swig_v)
{
  llsd_ops_t *arg1 = (llsd_ops_t *) 0 ;
  int (*result)(double const,void *const) = 0 ;
  
  struct swigargs {
    struct llsd_ops_s *arg1;
    long : 0;
    void *result;
  } *swig_a = (struct swigargs *) swig_v;
  
  arg1 = *(llsd_ops_t **)&swig_a->arg1; 
  
  result = (int (*)(double const,void *const)) ((arg1)->real_fn);
  *(int (**)(double const,void *const))&swig_a->result = result; 
}


void
_wrap_llsd_ops_t_uuid_fn_set(void *swig_v)
{
  llsd_ops_t *arg1 = (llsd_ops_t *) 0 ;
  int (*arg2)(uint8_t const [(16)],void *const) = (int (*)(uint8_t const [(16)],void *const)) 0 ;
  
  struct swigargs {
    struct llsd_ops_s *arg1;
    void *arg2;
  } *swig_a = (struct swigargs *) swig_v;
  
  arg1 = *(llsd_ops_t **)&swig_a->arg1; 
  arg2 = *(int (**)(uint8_t const [(16)],void *const))&swig_a->arg2; 
  
  if (arg1) (arg1)->uuid_fn = arg2;
  
}


void
_wrap_llsd_ops_t_uuid_fn_get(void *swig_v)
{
  llsd_ops_t *arg1 = (llsd_ops_t *) 0 ;
  int (*result)(uint8_t const [(16)],void *const) = 0 ;
  
  struct swigargs {
    struct llsd_ops_s *arg1;
    long : 0;
    void *result;
  } *swig_a = (struct swigargs *) swig_v;
  
  arg1 = *(llsd_ops_t **)&swig_a->arg1; 
  
  result = (int (*)(uint8_t const [(16)],void *const)) ((arg1)->uuid_fn);
  *(int (**)(uint8_t const [(16)],void *const))&swig_a->result = result; 
}


void
_wrap_llsd_ops_t_string_fn_set(void *swig_v)
{
  llsd_ops_t *arg1 = (llsd_ops_t *) 0 ;
  int (*arg2)(uint8_t const *,int const,void *const) = (int (*)(uint8_t const *,int const,void *const)) 0 ;
  
  struct swigargs {
    struct llsd_ops_s *arg1;
    void *arg2;
  } *swig_a = (struct swigargs *) swig_v;
  
  arg1 = *(llsd_ops_t **)&swig_a->arg1; 
  arg2 = *(int (**)(uint8_t const *,int const,void *const))&swig_a->arg2; 
  
  if (arg1) (arg1)->string_fn = arg2;
  
}


void
_wrap_llsd_ops_t_string_fn_get(void *swig_v)
{
  llsd_ops_t *arg1 = (llsd_ops_t *) 0 ;
  int (*result)(uint8_t const *,int const,void *const) = 0 ;
  
  struct swigargs {
    struct llsd_ops_s *arg1;
    long : 0;
    void *result;
  } *swig_a = (struct swigargs *) swig_v;
  
  arg1 = *(llsd_ops_t **)&swig_a->arg1; 
  
  result = (int (*)(uint8_t const *,int const,void *const)) ((arg1)->string_fn);
  *(int (**)(uint8_t const *,int const,void *const))&swig_a->result = result; 
}


void
_wrap_llsd_ops_t_date_fn_set(void *swig_v)
{
  llsd_ops_t *arg1 = (llsd_ops_t *) 0 ;
  int (*arg2)(double const,void *const) = (int (*)(double const,void *const)) 0 ;
  
  struct swigargs {
    struct llsd_ops_s *arg1;
    void *arg2;
  } *swig_a = (struct swigargs *) swig_v;
  
  arg1 = *(llsd_ops_t **)&swig_a->arg1; 
  arg2 = *(int (**)(double const,void *const))&swig_a->arg2; 
  
  if (arg1) (arg1)->date_fn = arg2;
  
}


void
_wrap_llsd_ops_t_date_fn_get(void *swig_v)
{
  llsd_ops_t *arg1 = (llsd_ops_t *) 0 ;
  int (*result)(double const,void *const) = 0 ;
  
  struct swigargs {
    struct llsd_ops_s *arg1;
    long : 0;
    void *result;
  } *swig_a = (struct swigargs *) swig_v;
  
  arg1 = *(llsd_ops_t **)&swig_a->arg1; 
  
  result = (int (*)(double const,void *const)) ((arg1)->date_fn);
  *(int (**)(double const,void *const))&swig_a->result = result; 
}


void
_wrap_llsd_ops_t_uri_fn_set(void *swig_v)
{
  llsd_ops_t *arg1 = (llsd_ops_t *) 0 ;
  int (*arg2)(uint8_t const *,int const,void *const) = (int (*)(uint8_t const *,int const,void *const)) 0 ;
  
  struct swigargs {
    struct llsd_ops_s *arg1;
    void *arg2;
  } *swig_a = (struct swigargs *) swig_v;
  
  arg1 = *(llsd_ops_t **)&swig_a->arg1; 
  arg2 = *(int (**)(uint8_t const *,int const,void *const))&swig_a->arg2; 
  
  if (arg1) (arg1)->uri_fn = arg2;
  
}


void
_wrap_llsd_ops_t_uri_fn_get(void *swig_v)
{
  llsd_ops_t *arg1 = (llsd_ops_t *) 0 ;
  int (*result)(uint8_t const *,int const,void *const) = 0 ;
  
  struct swigargs {
    struct llsd_ops_s *arg1;
    long : 0;
    void *result;
  } *swig_a = (struct swigargs *) swig_v;
  
  arg1 = *(llsd_ops_t **)&swig_a->arg1; 
  
  result = (int (*)(uint8_t const *,int const,void *const)) ((arg1)->uri_fn);
  *(int (**)(uint8_t const *,int const,void *const))&swig_a->result = result; 
}


void
_wrap_llsd_ops_t_binary_fn_set(void *swig_v)
{
  llsd_ops_t *arg1 = (llsd_ops_t *) 0 ;
  int (*arg2)(uint8_t const *,uint32_t const,int const,void *const) = (int (*)(uint8_t const *,uint32_t const,int const,void *const)) 0 ;
  
  struct swigargs {
    struct llsd_ops_s *arg1;
    void *arg2;
  } *swig_a = (struct swigargs *) swig_v;
  
  arg1 = *(llsd_ops_t **)&swig_a->arg1; 
  arg2 = *(int (**)(uint8_t const *,uint32_t const,int const,void *const))&swig_a->arg2; 
  
  if (arg1) (arg1)->binary_fn = arg2;
  
}


void
_wrap_llsd_ops_t_binary_fn_get(void *swig_v)
{
  llsd_ops_t *arg1 = (llsd_ops_t *) 0 ;
  int (*result)(uint8_t const *,uint32_t const,int const,void *const) = 0 ;
  
  struct swigargs {
    struct llsd_ops_s *arg1;
    long : 0;
    void *result;
  } *swig_a = (struct swigargs *) swig_v;
  
  arg1 = *(llsd_ops_t **)&swig_a->arg1; 
  
  result = (int (*)(uint8_t const *,uint32_t const,int const,void *const)) ((arg1)->binary_fn);
  *(int (**)(uint8_t const *,uint32_t const,int const,void *const))&swig_a->result = result; 
}


void
_wrap_llsd_ops_t_array_begin_fn_set(void *swig_v)
{
  llsd_ops_t *arg1 = (llsd_ops_t *) 0 ;
  int (*arg2)(uint32_t const,void *const) = (int (*)(uint32_t const,void *const)) 0 ;
  
  struct swigargs {
    struct llsd_ops_s *arg1;
    void *arg2;
  } *swig_a = (struct swigargs *) swig_v;
  
  arg1 = *(llsd_ops_t **)&swig_a->arg1; 
  arg2 = *(int (**)(uint32_t const,void *const))&swig_a->arg2; 
  
  if (arg1) (arg1)->array_begin_fn = arg2;
  
}


void
_wrap_llsd_ops_t_array_begin_fn_get(void *swig_v)
{
  llsd_ops_t *arg1 = (llsd_ops_t *) 0 ;
  int (*result)(uint32_t const,void *const) = 0 ;
  
  struct swigargs {
    struct llsd_ops_s *arg1;
    long : 0;
    void *result;
  } *swig_a = (struct swigargs *) swig_v;
  
  arg1 = *(llsd_ops_t **)&swig_a->arg1; 
  
  result = (int (*)(uint32_t const,void *const)) ((arg1)->array_begin_fn);
  *(int (**)(uint32_t const,void *const))&swig_a->result = result; 
}


void
_wrap_llsd_ops_t_array_value_begin_fn_set(void *swig_v)
{
  llsd_ops_t *arg1 = (llsd_ops_t *) 0 ;
  int (*arg2)(void *const) = (int (*)(void *const)) 0 ;
  
  struct swigargs {
    struct llsd_ops_s *arg1;
    void *arg2;
  } *swig_a = (struct swigargs *) swig_v;
  
  arg1 = *(llsd_ops_t **)&swig_a->arg1; 
  arg2 = *(int (**)(void *const))&swig_a->arg2; 
  
  if (arg1) (arg1)->array_value_begin_fn = arg2;
  
}


void
_wrap_llsd_ops_t_array_value_begin_fn_get(void *swig_v)
{
  llsd_ops_t *arg1 = (llsd_ops_t *) 0 ;
  int (*result)(void *const) = 0 ;
  
  struct swigargs {
    struct llsd_ops_s *arg1;
    long : 0;
    void *result;
  } *swig_a = (struct swigargs *) swig_v;
  
  arg1 = *(llsd_ops_t **)&swig_a->arg1; 
  
  result = (int (*)(void *const)) ((arg1)->array_value_begin_fn);
  *(int (**)(void *const))&swig_a->result = result; 
}


void
_wrap_llsd_ops_t_array_value_end_fn_set(void *swig_v)
{
  llsd_ops_t *arg1 = (llsd_ops_t *) 0 ;
  int (*arg2)(void *const) = (int (*)(void *const)) 0 ;
  
  struct swigargs {
    struct llsd_ops_s *arg1;
    void *arg2;
  } *swig_a = (struct swigargs *) swig_v;
  
  arg1 = *(llsd_ops_t **)&swig_a->arg1; 
  arg2 = *(int (**)(void *const))&swig_a->arg2; 
  
  if (arg1) (arg1)->array_value_end_fn = arg2;
  
}


void
_wrap_llsd_ops_t_array_value_end_fn_get(void *swig_v)
{
  llsd_ops_t *arg1 = (llsd_ops_t *) 0 ;
  int (*result)(void *const) = 0 ;
  
  struct swigargs {
    struct llsd_ops_s *arg1;
    long : 0;
    void *result;
  } *swig_a = (struct swigargs *) swig_v;
  
  arg1 = *(llsd_ops_t **)&swig_a->arg1; 
  
  result = (int (*)(void *const)) ((arg1)->array_value_end_fn);
  *(int (**)(void *const))&swig_a->result = result; 
}


void
_wrap_llsd_ops_t_array_end_fn_set(void *swig_v)
{
  llsd_ops_t *arg1 = (llsd_ops_t *) 0 ;
  int (*arg2)(uint32_t const,void *const) = (int (*)(uint32_t const,void *const)) 0 ;
  
  struct swigargs {
    struct llsd_ops_s *arg1;
    void *arg2;
  } *swig_a = (struct swigargs *) swig_v;
  
  arg1 = *(llsd_ops_t **)&swig_a->arg1; 
  arg2 = *(int (**)(uint32_t const,void *const))&swig_a->arg2; 
  
  if (arg1) (arg1)->array_end_fn = arg2;
  
}


void
_wrap_llsd_ops_t_array_end_fn_get(void *swig_v)
{
  llsd_ops_t *arg1 = (llsd_ops_t *) 0 ;
  int (*result)(uint32_t const,void *const) = 0 ;
  
  struct swigargs {
    struct llsd_ops_s *arg1;
    long : 0;
    void *result;
  } *swig_a = (struct swigargs *) swig_v;
  
  arg1 = *(llsd_ops_t **)&swig_a->arg1; 
  
  result = (int (*)(uint32_t const,void *const)) ((arg1)->array_end_fn);
  *(int (**)(uint32_t const,void *const))&swig_a->result = result; 
}


void
_wrap_llsd_ops_t_map_begin_fn_set(void *swig_v)
{
  llsd_ops_t *arg1 = (llsd_ops_t *) 0 ;
  int (*arg2)(uint32_t const,void *const) = (int (*)(uint32_t const,void *const)) 0 ;
  
  struct swigargs {
    struct llsd_ops_s *arg1;
    void *arg2;
  } *swig_a = (struct swigargs *) swig_v;
  
  arg1 = *(llsd_ops_t **)&swig_a->arg1; 
  arg2 = *(int (**)(uint32_t const,void *const))&swig_a->arg2; 
  
  if (arg1) (arg1)->map_begin_fn = arg2;
  
}


void
_wrap_llsd_ops_t_map_begin_fn_get(void *swig_v)
{
  llsd_ops_t *arg1 = (llsd_ops_t *) 0 ;
  int (*result)(uint32_t const,void *const) = 0 ;
  
  struct swigargs {
    struct llsd_ops_s *arg1;
    long : 0;
    void *result;
  } *swig_a = (struct swigargs *) swig_v;
  
  arg1 = *(llsd_ops_t **)&swig_a->arg1; 
  
  result = (int (*)(uint32_t const,void *const)) ((arg1)->map_begin_fn);
  *(int (**)(uint32_t const,void *const))&swig_a->result = result; 
}


void
_wrap_llsd_ops_t_map_key_begin_fn_set(void *swig_v)
{
  llsd_ops_t *arg1 = (llsd_ops_t *) 0 ;
  int (*arg2)(void *const) = (int (*)(void *const)) 0 ;
  
  struct swigargs {
    struct llsd_ops_s *arg1;
    void *arg2;
  } *swig_a = (struct swigargs *) swig_v;
  
  arg1 = *(llsd_ops_t **)&swig_a->arg1; 
  arg2 = *(int (**)(void *const))&swig_a->arg2; 
  
  if (arg1) (arg1)->map_key_begin_fn = arg2;
  
}


void
_wrap_llsd_ops_t_map_key_begin_fn_get(void *swig_v)
{
  llsd_ops_t *arg1 = (llsd_ops_t *) 0 ;
  int (*result)(void *const) = 0 ;
  
  struct swigargs {
    struct llsd_ops_s *arg1;
    long : 0;
    void *result;
  } *swig_a = (struct swigargs *) swig_v;
  
  arg1 = *(llsd_ops_t **)&swig_a->arg1; 
  
  result = (int (*)(void *const)) ((arg1)->map_key_begin_fn);
  *(int (**)(void *const))&swig_a->result = result; 
}


void
_wrap_llsd_ops_t_map_key_end_fn_set(void *swig_v)
{
  llsd_ops_t *arg1 = (llsd_ops_t *) 0 ;
  int (*arg2)(void *const) = (int (*)(void *const)) 0 ;
  
  struct swigargs {
    struct llsd_ops_s *arg1;
    void *arg2;
  } *swig_a = (struct swigargs *) swig_v;
  
  arg1 = *(llsd_ops_t **)&swig_a->arg1; 
  arg2 = *(int (**)(void *const))&swig_a->arg2; 
  
  if (arg1) (arg1)->map_key_end_fn = arg2;
  
}


void
_wrap_llsd_ops_t_map_key_end_fn_get(void *swig_v)
{
  llsd_ops_t *arg1 = (llsd_ops_t *) 0 ;
  int (*result)(void *const) = 0 ;
  
  struct swigargs {
    struct llsd_ops_s *arg1;
    long : 0;
    void *result;
  } *swig_a = (struct swigargs *) swig_v;
  
  arg1 = *(llsd_ops_t **)&swig_a->arg1; 
  
  result = (int (*)(void *const)) ((arg1)->map_key_end_fn);
  *(int (**)(void *const))&swig_a->result = result; 
}


void
_wrap_llsd_ops_t_map_value_begin_fn_set(void *swig_v)
{
  llsd_ops_t *arg1 = (llsd_ops_t *) 0 ;
  int (*arg2)(void *const) = (int (*)(void *const)) 0 ;
  
  struct swigargs {
    struct llsd_ops_s *arg1;
    void *arg2;
  } *swig_a = (struct swigargs *) swig_v;
  
  arg1 = *(llsd_ops_t **)&swig_a->arg1; 
  arg2 = *(int (**)(void *const))&swig_a->arg2; 
  
  if (arg1) (arg1)->map_value_begin_fn = arg2;
  
}


void
_wrap_llsd_ops_t_map_value_begin_fn_get(void *swig_v)
{
  llsd_ops_t *arg1 = (llsd_ops_t *) 0 ;
  int (*result)(void *const) = 0 ;
  
  struct swigargs {
    struct llsd_ops_s *arg1;
    long : 0;
    void *result;
  } *swig_a = (struct swigargs *) swig_v;
  
  arg1 = *(llsd_ops_t **)&swig_a->arg1; 
  
  result = (int (*)(void *const)) ((arg1)->map_value_begin_fn);
  *(int (**)(void *const))&swig_a->result = result; 
}


void
_wrap_llsd_ops_t_map_value_end_fn_set(void *swig_v)
{
  llsd_ops_t *arg1 = (llsd_ops_t *) 0 ;
  int (*arg2)(void *const) = (int (*)(void *const)) 0 ;
  
  struct swigargs {
    struct llsd_ops_s *arg1;
    void *arg2;
  } *swig_a = (struct swigargs *) swig_v;
  
  arg1 = *(llsd_ops_t **)&swig_a->arg1; 
  arg2 = *(int (**)(void *const))&swig_a->arg2; 
  
  if (arg1) (arg1)->map_value_end_fn = arg2;
  
}


void
_wrap_llsd_ops_t_map_value_end_fn_get(void *swig_v)
{
  llsd_ops_t *arg1 = (llsd_ops_t *) 0 ;
  int (*result)(void *const) = 0 ;
  
  struct swigargs {
    struct llsd_ops_s *arg1;
    long : 0;
    void *result;
  } *swig_a = (struct swigargs *) swig_v;
  
  arg1 = *(llsd_ops_t **)&swig_a->arg1; 
  
  result = (int (*)(void *const)) ((arg1)->map_value_end_fn);
  *(int (**)(void *const))&swig_a->result = result; 
}


void
_wrap_llsd_ops_t_map_end_fn_set(void *swig_v)
{
  llsd_ops_t *arg1 = (llsd_ops_t *) 0 ;
  int (*arg2)(uint32_t const,void *const) = (int (*)(uint32_t const,void *const)) 0 ;
  
  struct swigargs {
    struct llsd_ops_s *arg1;
    void *arg2;
  } *swig_a = (struct swigargs *) swig_v;
  
  arg1 = *(llsd_ops_t **)&swig_a->arg1; 
  arg2 = *(int (**)(uint32_t const,void *const))&swig_a->arg2; 
  
  if (arg1) (arg1)->map_end_fn = arg2;
  
}


void
_wrap_llsd_ops_t_map_end_fn_get(void *swig_v)
{
  llsd_ops_t *arg1 = (llsd_ops_t *) 0 ;
  int (*result)(uint32_t const,void *const) = 0 ;
  
  struct swigargs {
    struct llsd_ops_s *arg1;
    long : 0;
    void *result;
  } *swig_a = (struct swigargs *) swig_v;
  
  arg1 = *(llsd_ops_t **)&swig_a->arg1; 
  
  result = (int (*)(uint32_t const,void *const)) ((arg1)->map_end_fn);
  *(int (**)(uint32_t const,void *const))&swig_a->result = result; 
}


void
_wrap_new_llsd_ops_t(void *swig_v)
{
  llsd_ops_t *result = 0 ;
  
  struct swigargs {
    long : 0;
    struct llsd_ops_s *result;
  } *swig_a = (struct swigargs *) swig_v;
  
  
  result = (llsd_ops_t *)calloc(1, sizeof(llsd_ops_t));
  *(llsd_ops_t **)&swig_a->result = result; 
}


void
_wrap_delete_llsd_ops_t(void *swig_v)
{
  llsd_ops_t *arg1 = (llsd_ops_t *) 0 ;
  
  struct swigargs {
    struct llsd_ops_s *arg1;
  } *swig_a = (struct swigargs *) swig_v;
  
  arg1 = *(llsd_ops_t **)&swig_a->arg1; 
  
  free((char *) arg1);
  
}


void
_wrap_TOP_LEVEL(void *swig_v)
{
  enum state_e result;
  
  struct swigargs {
    long : 0;
    enum state_e result;
  } *swig_a = (struct swigargs *) swig_v;
  
  
  result = TOP_LEVEL;
  
  swig_a->result = result; 
}


void
_wrap_ARRAY_BEGIN(void *swig_v)
{
  enum state_e result;
  
  struct swigargs {
    long : 0;
    enum state_e result;
  } *swig_a = (struct swigargs *) swig_v;
  
  
  result = ARRAY_BEGIN;
  
  swig_a->result = result; 
}


void
_wrap_ARRAY_VALUE_BEGIN(void *swig_v)
{
  enum state_e result;
  
  struct swigargs {
    long : 0;
    enum state_e result;
  } *swig_a = (struct swigargs *) swig_v;
  
  
  result = ARRAY_VALUE_BEGIN;
  
  swig_a->result = result; 
}


void
_wrap_ARRAY_VALUE(void *swig_v)
{
  enum state_e result;
  
  struct swigargs {
    long : 0;
    enum state_e result;
  } *swig_a = (struct swigargs *) swig_v;
  
  
  result = ARRAY_VALUE;
  
  swig_a->result = result; 
}


void
_wrap_ARRAY_VALUE_END(void *swig_v)
{
  enum state_e result;
  
  struct swigargs {
    long : 0;
    enum state_e result;
  } *swig_a = (struct swigargs *) swig_v;
  
  
  result = ARRAY_VALUE_END;
  
  swig_a->result = result; 
}


void
_wrap_ARRAY_END(void *swig_v)
{
  enum state_e result;
  
  struct swigargs {
    long : 0;
    enum state_e result;
  } *swig_a = (struct swigargs *) swig_v;
  
  
  result = ARRAY_END;
  
  swig_a->result = result; 
}


void
_wrap_MAP_BEGIN(void *swig_v)
{
  enum state_e result;
  
  struct swigargs {
    long : 0;
    enum state_e result;
  } *swig_a = (struct swigargs *) swig_v;
  
  
  result = MAP_BEGIN;
  
  swig_a->result = result; 
}


void
_wrap_MAP_KEY_BEGIN(void *swig_v)
{
  enum state_e result;
  
  struct swigargs {
    long : 0;
    enum state_e result;
  } *swig_a = (struct swigargs *) swig_v;
  
  
  result = MAP_KEY_BEGIN;
  
  swig_a->result = result; 
}


void
_wrap_MAP_KEY(void *swig_v)
{
  enum state_e result;
  
  struct swigargs {
    long : 0;
    enum state_e result;
  } *swig_a = (struct swigargs *) swig_v;
  
  
  result = MAP_KEY;
  
  swig_a->result = result; 
}


void
_wrap_MAP_KEY_END(void *swig_v)
{
  enum state_e result;
  
  struct swigargs {
    long : 0;
    enum state_e result;
  } *swig_a = (struct swigargs *) swig_v;
  
  
  result = MAP_KEY_END;
  
  swig_a->result = result; 
}


void
_wrap_MAP_VALUE_BEGIN(void *swig_v)
{
  enum state_e result;
  
  struct swigargs {
    long : 0;
    enum state_e result;
  } *swig_a = (struct swigargs *) swig_v;
  
  
  result = MAP_VALUE_BEGIN;
  
  swig_a->result = result; 
}


void
_wrap_MAP_VALUE(void *swig_v)
{
  enum state_e result;
  
  struct swigargs {
    long : 0;
    enum state_e result;
  } *swig_a = (struct swigargs *) swig_v;
  
  
  result = MAP_VALUE;
  
  swig_a->result = result; 
}


void
_wrap_MAP_VALUE_END(void *swig_v)
{
  enum state_e result;
  
  struct swigargs {
    long : 0;
    enum state_e result;
  } *swig_a = (struct swigargs *) swig_v;
  
  
  result = MAP_VALUE_END;
  
  swig_a->result = result; 
}


void
_wrap_MAP_END(void *swig_v)
{
  enum state_e result;
  
  struct swigargs {
    long : 0;
    enum state_e result;
  } *swig_a = (struct swigargs *) swig_v;
  
  
  result = MAP_END;
  
  swig_a->result = result; 
}


void
_wrap_llsd_serialize_to_file(void *swig_v)
{
  llsd_t *arg1 = (llsd_t *) (llsd_t *)0 ;
  FILE *arg2 = (FILE *) 0 ;
  llsd_serializer_t arg3 ;
  int arg4 ;
  int result;
  
  struct swigargs {
    struct llsd_s *arg1;
    FILE *arg2;
    llsd_serializer_t arg3;
    int arg4;
    long : 0;
    int result;
  } *swig_a = (struct swigargs *) swig_v;
  
  arg1 = *(llsd_t **)&swig_a->arg1; 
  arg2 = *(FILE **)&swig_a->arg2; 
  arg3 = (llsd_serializer_t)swig_a->arg3; 
  arg4 = (int)swig_a->arg4; 
  
  result = (int)llsd_serialize_to_file(arg1,arg2,arg3,arg4);
  swig_a->result = result; 
}


void
_wrap_llsd_parse_from_file(void *swig_v)
{
  FILE *arg1 = (FILE *) 0 ;
  llsd_t *result = 0 ;
  
  struct swigargs {
    FILE *arg1;
    long : 0;
    struct llsd_s *result;
  } *swig_a = (struct swigargs *) swig_v;
  
  arg1 = *(FILE **)&swig_a->arg1; 
  
  result = (llsd_t *)llsd_parse_from_file(arg1);
  *(llsd_t **)&swig_a->result = result; 
}


#ifdef __cplusplus
}
#endif

