/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 * 
 * This file is not intended to be easily readable and contains a number of 
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG 
 * interface file instead. 
 * ----------------------------------------------------------------------------- */

package llsd



import _ "runtime/cgo"



type _swig_fnptr *byte
type _swig_memberptr *byte

type Enum_SS_llsd_type_e int
func _swig_getLLSD_UNDEF() Enum_SS_llsd_type_e
var LLSD_UNDEF Enum_SS_llsd_type_e = _swig_getLLSD_UNDEF()
func _swig_getLLSD_BOOLEAN() Enum_SS_llsd_type_e
var LLSD_BOOLEAN Enum_SS_llsd_type_e = _swig_getLLSD_BOOLEAN()
func _swig_getLLSD_INTEGER() Enum_SS_llsd_type_e
var LLSD_INTEGER Enum_SS_llsd_type_e = _swig_getLLSD_INTEGER()
func _swig_getLLSD_REAL() Enum_SS_llsd_type_e
var LLSD_REAL Enum_SS_llsd_type_e = _swig_getLLSD_REAL()
func _swig_getLLSD_UUID() Enum_SS_llsd_type_e
var LLSD_UUID Enum_SS_llsd_type_e = _swig_getLLSD_UUID()
func _swig_getLLSD_STRING() Enum_SS_llsd_type_e
var LLSD_STRING Enum_SS_llsd_type_e = _swig_getLLSD_STRING()
func _swig_getLLSD_DATE() Enum_SS_llsd_type_e
var LLSD_DATE Enum_SS_llsd_type_e = _swig_getLLSD_DATE()
func _swig_getLLSD_URI() Enum_SS_llsd_type_e
var LLSD_URI Enum_SS_llsd_type_e = _swig_getLLSD_URI()
func _swig_getLLSD_BINARY() Enum_SS_llsd_type_e
var LLSD_BINARY Enum_SS_llsd_type_e = _swig_getLLSD_BINARY()
func _swig_getLLSD_ARRAY() Enum_SS_llsd_type_e
var LLSD_ARRAY Enum_SS_llsd_type_e = _swig_getLLSD_ARRAY()
func _swig_getLLSD_MAP() Enum_SS_llsd_type_e
var LLSD_MAP Enum_SS_llsd_type_e = _swig_getLLSD_MAP()
func _swig_getLLSD_TYPE_LAST() Enum_SS_llsd_type_e
var LLSD_TYPE_LAST Enum_SS_llsd_type_e = _swig_getLLSD_TYPE_LAST()
func _swig_getLLSD_TYPE_FIRST() Enum_SS_llsd_type_e
var LLSD_TYPE_FIRST Enum_SS_llsd_type_e = _swig_getLLSD_TYPE_FIRST()
func _swig_getLLSD_TYPE_COUNT() Enum_SS_llsd_type_e
var LLSD_TYPE_COUNT Enum_SS_llsd_type_e = _swig_getLLSD_TYPE_COUNT()
func _swig_getLLSD_TYPE_INVALID() Enum_SS_llsd_type_e
var LLSD_TYPE_INVALID Enum_SS_llsd_type_e = _swig_getLLSD_TYPE_INVALID()
func _swig_getLLSD_KEY() Enum_SS_llsd_type_e
var LLSD_KEY Enum_SS_llsd_type_e = _swig_getLLSD_KEY()
func _swig_getLLSD_LLSD() Enum_SS_llsd_type_e
var LLSD_LLSD Enum_SS_llsd_type_e = _swig_getLLSD_LLSD()
func GetLlsd_type_strings() uintptr
type Enum_SS_llsd_serializer_s int
func _swig_getLLSD_ENC_XML() Enum_SS_llsd_serializer_s
var LLSD_ENC_XML Enum_SS_llsd_serializer_s = _swig_getLLSD_ENC_XML()
func _swig_getLLSD_ENC_BINARY() Enum_SS_llsd_serializer_s
var LLSD_ENC_BINARY Enum_SS_llsd_serializer_s = _swig_getLLSD_ENC_BINARY()
func _swig_getLLSD_ENC_NOTATION() Enum_SS_llsd_serializer_s
var LLSD_ENC_NOTATION Enum_SS_llsd_serializer_s = _swig_getLLSD_ENC_NOTATION()
func _swig_getLLSD_ENC_JSON() Enum_SS_llsd_serializer_s
var LLSD_ENC_JSON Enum_SS_llsd_serializer_s = _swig_getLLSD_ENC_JSON()
func _swig_getLLSD_ENC_LAST() Enum_SS_llsd_serializer_s
var LLSD_ENC_LAST Enum_SS_llsd_serializer_s = _swig_getLLSD_ENC_LAST()
func _swig_getLLSD_ENC_FIRST() Enum_SS_llsd_serializer_s
var LLSD_ENC_FIRST Enum_SS_llsd_serializer_s = _swig_getLLSD_ENC_FIRST()
func _swig_getLLSD_ENC_COUNT() Enum_SS_llsd_serializer_s
var LLSD_ENC_COUNT Enum_SS_llsd_serializer_s = _swig_getLLSD_ENC_COUNT()
type Enum_SS_llsd_bin_enc_s int
func _swig_getLLSD_NONE() Enum_SS_llsd_bin_enc_s
var LLSD_NONE Enum_SS_llsd_bin_enc_s = _swig_getLLSD_NONE()
func _swig_getLLSD_BASE16() Enum_SS_llsd_bin_enc_s
var LLSD_BASE16 Enum_SS_llsd_bin_enc_s = _swig_getLLSD_BASE16()
func _swig_getLLSD_BASE64() Enum_SS_llsd_bin_enc_s
var LLSD_BASE64 Enum_SS_llsd_bin_enc_s = _swig_getLLSD_BASE64()
func _swig_getLLSD_BASE85() Enum_SS_llsd_bin_enc_s
var LLSD_BASE85 Enum_SS_llsd_bin_enc_s = _swig_getLLSD_BASE85()
func _swig_getLLSD_BIN_ENC_LAST() Enum_SS_llsd_bin_enc_s
var LLSD_BIN_ENC_LAST Enum_SS_llsd_bin_enc_s = _swig_getLLSD_BIN_ENC_LAST()
func _swig_getLLSD_BIN_ENC_FIRST() Enum_SS_llsd_bin_enc_s
var LLSD_BIN_ENC_FIRST Enum_SS_llsd_bin_enc_s = _swig_getLLSD_BIN_ENC_FIRST()
func _swig_getLLSD_BIN_ENC_COUNT() Enum_SS_llsd_bin_enc_s
var LLSD_BIN_ENC_COUNT Enum_SS_llsd_bin_enc_s = _swig_getLLSD_BIN_ENC_COUNT()
func _swig_getLLSD_RAW() Enum_SS_llsd_bin_enc_s
var LLSD_RAW Enum_SS_llsd_bin_enc_s = _swig_getLLSD_RAW()
func GetLlsd_xml_bin_enc_type_strings() uintptr
func GetLlsd_notation_bin_enc_type_strings() uintptr
func _swig_getUUID_LEN() int
var UUID_LEN int = _swig_getUUID_LEN()
func _swig_getUUID_STR_LEN() int
var UUID_STR_LEN int = _swig_getUUID_STR_LEN()
func _swig_getDATE_STR_LEN() int
var DATE_STR_LEN int = _swig_getDATE_STR_LEN()
func _swig_wrap_llsd_new(Enum_SS_llsd_type_e) SwigcptrStruct_SS_llsd_s

func Llsd_new(arg1 Enum_SS_llsd_type_e) Struct_SS_llsd_s {
	return _swig_wrap_llsd_new(arg1)
}

func _swig_wrap_llsd_delete(uintptr)

func Llsd_delete(arg1 uintptr) {
	_swig_wrap_llsd_delete(arg1)
}

func _swig_wrap_llsd_get_type(uintptr) Enum_SS_llsd_type_e

func Llsd_get_type(arg1 Struct_SS_llsd_s) Enum_SS_llsd_type_e {
	return _swig_wrap_llsd_get_type(arg1.Swigcptr())
}

func _swig_wrap_llsd_get_type_string(Enum_SS_llsd_type_e) SwigcptrInt8_t

func Llsd_get_type_string(arg1 Enum_SS_llsd_type_e) Int8_t {
	return _swig_wrap_llsd_get_type_string(arg1)
}

func _swig_wrap_llsd_get_bin_enc_type_string(Enum_SS_llsd_bin_enc_s, Enum_SS_llsd_serializer_s) SwigcptrInt8_t

func Llsd_get_bin_enc_type_string(arg1 Enum_SS_llsd_bin_enc_s, arg2 Enum_SS_llsd_serializer_s) Int8_t {
	return _swig_wrap_llsd_get_bin_enc_type_string(arg1, arg2)
}

type SwigcptrLlsd_itr_t uintptr

func (p SwigcptrLlsd_itr_t) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrLlsd_itr_t) SwigIsLlsd_itr_t() {
}

func _swig_wrap_llsd_itr_t_li_set(SwigcptrLlsd_itr_t, uintptr)

func (arg1 SwigcptrLlsd_itr_t) SetLi(arg2 List_itr_t) {
	_swig_wrap_llsd_itr_t_li_set(arg1, arg2.Swigcptr())
}

func _swig_wrap_llsd_itr_t_li_get(SwigcptrLlsd_itr_t) SwigcptrList_itr_t

func (arg1 SwigcptrLlsd_itr_t) GetLi() List_itr_t {
	return _swig_wrap_llsd_itr_t_li_get(arg1)
}

func _swig_wrap_llsd_itr_t_hi_set(SwigcptrLlsd_itr_t, uintptr)

func (arg1 SwigcptrLlsd_itr_t) SetHi(arg2 Ht_itr_t) {
	_swig_wrap_llsd_itr_t_hi_set(arg1, arg2.Swigcptr())
}

func _swig_wrap_llsd_itr_t_hi_get(SwigcptrLlsd_itr_t) SwigcptrHt_itr_t

func (arg1 SwigcptrLlsd_itr_t) GetHi() Ht_itr_t {
	return _swig_wrap_llsd_itr_t_hi_get(arg1)
}

func _swig_wrap_new_llsd_itr_t() SwigcptrLlsd_itr_t

func NewLlsd_itr_t() Llsd_itr_t {
	return _swig_wrap_new_llsd_itr_t()
}

func _swig_wrap_delete_llsd_itr_t(uintptr)

func DeleteLlsd_itr_t(arg1 Llsd_itr_t) {
	_swig_wrap_delete_llsd_itr_t(arg1.Swigcptr())
}

type Llsd_itr_t interface {
	Swigcptr() uintptr
	SwigIsLlsd_itr_t()
	SetLi(arg2 List_itr_t)
	GetLi() List_itr_t
	SetHi(arg2 Ht_itr_t)
	GetHi() Ht_itr_t
}

func _swig_wrap_llsd_array_append(uintptr, uintptr) int

func Llsd_array_append(arg1 Struct_SS_llsd_s, arg2 Struct_SS_llsd_s) int {
	return _swig_wrap_llsd_array_append(arg1.Swigcptr(), arg2.Swigcptr())
}

func _swig_wrap_llsd_array_unappend(uintptr) int

func Llsd_array_unappend(arg1 Struct_SS_llsd_s) int {
	return _swig_wrap_llsd_array_unappend(arg1.Swigcptr())
}

func _swig_wrap_llsd_map_insert(uintptr, uintptr, uintptr) int

func Llsd_map_insert(arg1 Struct_SS_llsd_s, arg2 Struct_SS_llsd_s, arg3 Struct_SS_llsd_s) int {
	return _swig_wrap_llsd_map_insert(arg1.Swigcptr(), arg2.Swigcptr(), arg3.Swigcptr())
}

func _swig_wrap_llsd_map_remove(uintptr, uintptr) int

func Llsd_map_remove(arg1 Struct_SS_llsd_s, arg2 Struct_SS_llsd_s) int {
	return _swig_wrap_llsd_map_remove(arg1.Swigcptr(), arg2.Swigcptr())
}

func _swig_wrap_llsd_itr_begin(uintptr) SwigcptrLlsd_itr_t

func Llsd_itr_begin(arg1 Struct_SS_llsd_s) Llsd_itr_t {
	return _swig_wrap_llsd_itr_begin(arg1.Swigcptr())
}

func _swig_wrap_llsd_itr_end(uintptr) SwigcptrLlsd_itr_t

func Llsd_itr_end(arg1 Struct_SS_llsd_s) Llsd_itr_t {
	return _swig_wrap_llsd_itr_end(arg1.Swigcptr())
}

func _swig_wrap_llsd_itr_rbegin(uintptr) SwigcptrLlsd_itr_t

func Llsd_itr_rbegin(arg1 Struct_SS_llsd_s) Llsd_itr_t {
	return _swig_wrap_llsd_itr_rbegin(arg1.Swigcptr())
}

func _swig_wrap_llsd_itr_next(uintptr, uintptr) SwigcptrLlsd_itr_t

func Llsd_itr_next(arg1 Struct_SS_llsd_s, arg2 Llsd_itr_t) Llsd_itr_t {
	return _swig_wrap_llsd_itr_next(arg1.Swigcptr(), arg2.Swigcptr())
}

func _swig_wrap_llsd_itr_rnext(uintptr, uintptr) SwigcptrLlsd_itr_t

func Llsd_itr_rnext(arg1 Struct_SS_llsd_s, arg2 Llsd_itr_t) Llsd_itr_t {
	return _swig_wrap_llsd_itr_rnext(arg1.Swigcptr(), arg2.Swigcptr())
}

func _swig_wrap_llsd_get(uintptr, uintptr, uintptr, uintptr) int

func Llsd_get(arg1 Struct_SS_llsd_s, arg2 Llsd_itr_t, arg3 Struct_SS_llsd_s, arg4 Struct_SS_llsd_s) int {
	return _swig_wrap_llsd_get(arg1.Swigcptr(), arg2.Swigcptr(), arg3.Swigcptr(), arg4.Swigcptr())
}

func _swig_wrap_llsd_map_find_llsd(uintptr, uintptr) SwigcptrStruct_SS_llsd_s

func Llsd_map_find_llsd(arg1 Struct_SS_llsd_s, arg2 Struct_SS_llsd_s) Struct_SS_llsd_s {
	return _swig_wrap_llsd_map_find_llsd(arg1.Swigcptr(), arg2.Swigcptr())
}

func _swig_wrap_llsd_map_find(uintptr, uintptr) SwigcptrStruct_SS_llsd_s

func Llsd_map_find(arg1 Struct_SS_llsd_s, arg2 Uint8_t) Struct_SS_llsd_s {
	return _swig_wrap_llsd_map_find(arg1.Swigcptr(), arg2.Swigcptr())
}

func _swig_wrap_llsd_as_boolean(uintptr, *int) int

func Llsd_as_boolean(arg1 Struct_SS_llsd_s, arg2 *int) int {
	return _swig_wrap_llsd_as_boolean(arg1.Swigcptr(), arg2)
}

func _swig_wrap_llsd_as_integer(uintptr, uintptr) int

func Llsd_as_integer(arg1 Struct_SS_llsd_s, arg2 Int32_t) int {
	return _swig_wrap_llsd_as_integer(arg1.Swigcptr(), arg2.Swigcptr())
}

func _swig_wrap_llsd_as_double(uintptr, *float64) int

func Llsd_as_double(arg1 Struct_SS_llsd_s, arg2 *float64) int {
	return _swig_wrap_llsd_as_double(arg1.Swigcptr(), arg2)
}

func _swig_wrap_llsd_as_uuid(uintptr, uintptr) int

func Llsd_as_uuid(arg1 Struct_SS_llsd_s, arg2 Uint8_t) int {
	return _swig_wrap_llsd_as_uuid(arg1.Swigcptr(), arg2.Swigcptr())
}

func _swig_wrap_llsd_as_string(uintptr, uintptr) int

func Llsd_as_string(arg1 Struct_SS_llsd_s, arg2 Uint8_t) int {
	return _swig_wrap_llsd_as_string(arg1.Swigcptr(), arg2.Swigcptr())
}

func _swig_wrap_llsd_as_binary(uintptr, uintptr, uintptr) int

func Llsd_as_binary(arg1 Struct_SS_llsd_s, arg2 Uint8_t, arg3 Uint32_t) int {
	return _swig_wrap_llsd_as_binary(arg1.Swigcptr(), arg2.Swigcptr(), arg3.Swigcptr())
}

func _swig_wrap_llsd_equal(uintptr, uintptr) int

func Llsd_equal(arg1 Struct_SS_llsd_s, arg2 Struct_SS_llsd_s) int {
	return _swig_wrap_llsd_equal(arg1.Swigcptr(), arg2.Swigcptr())
}

func _swig_wrap_llsd_get_count(uintptr) int

func Llsd_get_count(arg1 Struct_SS_llsd_s) int {
	return _swig_wrap_llsd_get_count(arg1.Swigcptr())
}

type SwigcptrLlsd_ops_t uintptr

func (p SwigcptrLlsd_ops_t) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrLlsd_ops_t) SwigIsLlsd_ops_t() {
}

func _swig_wrap_llsd_ops_t_undef_fn_set(SwigcptrLlsd_ops_t, _swig_fnptr)

func (arg1 SwigcptrLlsd_ops_t) SetUndef_fn(arg2 _swig_fnptr) {
	_swig_wrap_llsd_ops_t_undef_fn_set(arg1, arg2)
}

func _swig_wrap_llsd_ops_t_undef_fn_get(SwigcptrLlsd_ops_t) _swig_fnptr

func (arg1 SwigcptrLlsd_ops_t) GetUndef_fn() _swig_fnptr {
	return _swig_wrap_llsd_ops_t_undef_fn_get(arg1)
}

func _swig_wrap_llsd_ops_t_boolean_fn_set(SwigcptrLlsd_ops_t, _swig_fnptr)

func (arg1 SwigcptrLlsd_ops_t) SetBoolean_fn(arg2 _swig_fnptr) {
	_swig_wrap_llsd_ops_t_boolean_fn_set(arg1, arg2)
}

func _swig_wrap_llsd_ops_t_boolean_fn_get(SwigcptrLlsd_ops_t) _swig_fnptr

func (arg1 SwigcptrLlsd_ops_t) GetBoolean_fn() _swig_fnptr {
	return _swig_wrap_llsd_ops_t_boolean_fn_get(arg1)
}

func _swig_wrap_llsd_ops_t_integer_fn_set(SwigcptrLlsd_ops_t, _swig_fnptr)

func (arg1 SwigcptrLlsd_ops_t) SetInteger_fn(arg2 _swig_fnptr) {
	_swig_wrap_llsd_ops_t_integer_fn_set(arg1, arg2)
}

func _swig_wrap_llsd_ops_t_integer_fn_get(SwigcptrLlsd_ops_t) _swig_fnptr

func (arg1 SwigcptrLlsd_ops_t) GetInteger_fn() _swig_fnptr {
	return _swig_wrap_llsd_ops_t_integer_fn_get(arg1)
}

func _swig_wrap_llsd_ops_t_real_fn_set(SwigcptrLlsd_ops_t, _swig_fnptr)

func (arg1 SwigcptrLlsd_ops_t) SetReal_fn(arg2 _swig_fnptr) {
	_swig_wrap_llsd_ops_t_real_fn_set(arg1, arg2)
}

func _swig_wrap_llsd_ops_t_real_fn_get(SwigcptrLlsd_ops_t) _swig_fnptr

func (arg1 SwigcptrLlsd_ops_t) GetReal_fn() _swig_fnptr {
	return _swig_wrap_llsd_ops_t_real_fn_get(arg1)
}

func _swig_wrap_llsd_ops_t_uuid_fn_set(SwigcptrLlsd_ops_t, _swig_fnptr)

func (arg1 SwigcptrLlsd_ops_t) SetUuid_fn(arg2 _swig_fnptr) {
	_swig_wrap_llsd_ops_t_uuid_fn_set(arg1, arg2)
}

func _swig_wrap_llsd_ops_t_uuid_fn_get(SwigcptrLlsd_ops_t) _swig_fnptr

func (arg1 SwigcptrLlsd_ops_t) GetUuid_fn() _swig_fnptr {
	return _swig_wrap_llsd_ops_t_uuid_fn_get(arg1)
}

func _swig_wrap_llsd_ops_t_string_fn_set(SwigcptrLlsd_ops_t, _swig_fnptr)

func (arg1 SwigcptrLlsd_ops_t) SetString_fn(arg2 _swig_fnptr) {
	_swig_wrap_llsd_ops_t_string_fn_set(arg1, arg2)
}

func _swig_wrap_llsd_ops_t_string_fn_get(SwigcptrLlsd_ops_t) _swig_fnptr

func (arg1 SwigcptrLlsd_ops_t) GetString_fn() _swig_fnptr {
	return _swig_wrap_llsd_ops_t_string_fn_get(arg1)
}

func _swig_wrap_llsd_ops_t_date_fn_set(SwigcptrLlsd_ops_t, _swig_fnptr)

func (arg1 SwigcptrLlsd_ops_t) SetDate_fn(arg2 _swig_fnptr) {
	_swig_wrap_llsd_ops_t_date_fn_set(arg1, arg2)
}

func _swig_wrap_llsd_ops_t_date_fn_get(SwigcptrLlsd_ops_t) _swig_fnptr

func (arg1 SwigcptrLlsd_ops_t) GetDate_fn() _swig_fnptr {
	return _swig_wrap_llsd_ops_t_date_fn_get(arg1)
}

func _swig_wrap_llsd_ops_t_uri_fn_set(SwigcptrLlsd_ops_t, _swig_fnptr)

func (arg1 SwigcptrLlsd_ops_t) SetUri_fn(arg2 _swig_fnptr) {
	_swig_wrap_llsd_ops_t_uri_fn_set(arg1, arg2)
}

func _swig_wrap_llsd_ops_t_uri_fn_get(SwigcptrLlsd_ops_t) _swig_fnptr

func (arg1 SwigcptrLlsd_ops_t) GetUri_fn() _swig_fnptr {
	return _swig_wrap_llsd_ops_t_uri_fn_get(arg1)
}

func _swig_wrap_llsd_ops_t_binary_fn_set(SwigcptrLlsd_ops_t, _swig_fnptr)

func (arg1 SwigcptrLlsd_ops_t) SetBinary_fn(arg2 _swig_fnptr) {
	_swig_wrap_llsd_ops_t_binary_fn_set(arg1, arg2)
}

func _swig_wrap_llsd_ops_t_binary_fn_get(SwigcptrLlsd_ops_t) _swig_fnptr

func (arg1 SwigcptrLlsd_ops_t) GetBinary_fn() _swig_fnptr {
	return _swig_wrap_llsd_ops_t_binary_fn_get(arg1)
}

func _swig_wrap_llsd_ops_t_array_begin_fn_set(SwigcptrLlsd_ops_t, _swig_fnptr)

func (arg1 SwigcptrLlsd_ops_t) SetArray_begin_fn(arg2 _swig_fnptr) {
	_swig_wrap_llsd_ops_t_array_begin_fn_set(arg1, arg2)
}

func _swig_wrap_llsd_ops_t_array_begin_fn_get(SwigcptrLlsd_ops_t) _swig_fnptr

func (arg1 SwigcptrLlsd_ops_t) GetArray_begin_fn() _swig_fnptr {
	return _swig_wrap_llsd_ops_t_array_begin_fn_get(arg1)
}

func _swig_wrap_llsd_ops_t_array_value_begin_fn_set(SwigcptrLlsd_ops_t, _swig_fnptr)

func (arg1 SwigcptrLlsd_ops_t) SetArray_value_begin_fn(arg2 _swig_fnptr) {
	_swig_wrap_llsd_ops_t_array_value_begin_fn_set(arg1, arg2)
}

func _swig_wrap_llsd_ops_t_array_value_begin_fn_get(SwigcptrLlsd_ops_t) _swig_fnptr

func (arg1 SwigcptrLlsd_ops_t) GetArray_value_begin_fn() _swig_fnptr {
	return _swig_wrap_llsd_ops_t_array_value_begin_fn_get(arg1)
}

func _swig_wrap_llsd_ops_t_array_value_end_fn_set(SwigcptrLlsd_ops_t, _swig_fnptr)

func (arg1 SwigcptrLlsd_ops_t) SetArray_value_end_fn(arg2 _swig_fnptr) {
	_swig_wrap_llsd_ops_t_array_value_end_fn_set(arg1, arg2)
}

func _swig_wrap_llsd_ops_t_array_value_end_fn_get(SwigcptrLlsd_ops_t) _swig_fnptr

func (arg1 SwigcptrLlsd_ops_t) GetArray_value_end_fn() _swig_fnptr {
	return _swig_wrap_llsd_ops_t_array_value_end_fn_get(arg1)
}

func _swig_wrap_llsd_ops_t_array_end_fn_set(SwigcptrLlsd_ops_t, _swig_fnptr)

func (arg1 SwigcptrLlsd_ops_t) SetArray_end_fn(arg2 _swig_fnptr) {
	_swig_wrap_llsd_ops_t_array_end_fn_set(arg1, arg2)
}

func _swig_wrap_llsd_ops_t_array_end_fn_get(SwigcptrLlsd_ops_t) _swig_fnptr

func (arg1 SwigcptrLlsd_ops_t) GetArray_end_fn() _swig_fnptr {
	return _swig_wrap_llsd_ops_t_array_end_fn_get(arg1)
}

func _swig_wrap_llsd_ops_t_map_begin_fn_set(SwigcptrLlsd_ops_t, _swig_fnptr)

func (arg1 SwigcptrLlsd_ops_t) SetMap_begin_fn(arg2 _swig_fnptr) {
	_swig_wrap_llsd_ops_t_map_begin_fn_set(arg1, arg2)
}

func _swig_wrap_llsd_ops_t_map_begin_fn_get(SwigcptrLlsd_ops_t) _swig_fnptr

func (arg1 SwigcptrLlsd_ops_t) GetMap_begin_fn() _swig_fnptr {
	return _swig_wrap_llsd_ops_t_map_begin_fn_get(arg1)
}

func _swig_wrap_llsd_ops_t_map_key_begin_fn_set(SwigcptrLlsd_ops_t, _swig_fnptr)

func (arg1 SwigcptrLlsd_ops_t) SetMap_key_begin_fn(arg2 _swig_fnptr) {
	_swig_wrap_llsd_ops_t_map_key_begin_fn_set(arg1, arg2)
}

func _swig_wrap_llsd_ops_t_map_key_begin_fn_get(SwigcptrLlsd_ops_t) _swig_fnptr

func (arg1 SwigcptrLlsd_ops_t) GetMap_key_begin_fn() _swig_fnptr {
	return _swig_wrap_llsd_ops_t_map_key_begin_fn_get(arg1)
}

func _swig_wrap_llsd_ops_t_map_key_end_fn_set(SwigcptrLlsd_ops_t, _swig_fnptr)

func (arg1 SwigcptrLlsd_ops_t) SetMap_key_end_fn(arg2 _swig_fnptr) {
	_swig_wrap_llsd_ops_t_map_key_end_fn_set(arg1, arg2)
}

func _swig_wrap_llsd_ops_t_map_key_end_fn_get(SwigcptrLlsd_ops_t) _swig_fnptr

func (arg1 SwigcptrLlsd_ops_t) GetMap_key_end_fn() _swig_fnptr {
	return _swig_wrap_llsd_ops_t_map_key_end_fn_get(arg1)
}

func _swig_wrap_llsd_ops_t_map_value_begin_fn_set(SwigcptrLlsd_ops_t, _swig_fnptr)

func (arg1 SwigcptrLlsd_ops_t) SetMap_value_begin_fn(arg2 _swig_fnptr) {
	_swig_wrap_llsd_ops_t_map_value_begin_fn_set(arg1, arg2)
}

func _swig_wrap_llsd_ops_t_map_value_begin_fn_get(SwigcptrLlsd_ops_t) _swig_fnptr

func (arg1 SwigcptrLlsd_ops_t) GetMap_value_begin_fn() _swig_fnptr {
	return _swig_wrap_llsd_ops_t_map_value_begin_fn_get(arg1)
}

func _swig_wrap_llsd_ops_t_map_value_end_fn_set(SwigcptrLlsd_ops_t, _swig_fnptr)

func (arg1 SwigcptrLlsd_ops_t) SetMap_value_end_fn(arg2 _swig_fnptr) {
	_swig_wrap_llsd_ops_t_map_value_end_fn_set(arg1, arg2)
}

func _swig_wrap_llsd_ops_t_map_value_end_fn_get(SwigcptrLlsd_ops_t) _swig_fnptr

func (arg1 SwigcptrLlsd_ops_t) GetMap_value_end_fn() _swig_fnptr {
	return _swig_wrap_llsd_ops_t_map_value_end_fn_get(arg1)
}

func _swig_wrap_llsd_ops_t_map_end_fn_set(SwigcptrLlsd_ops_t, _swig_fnptr)

func (arg1 SwigcptrLlsd_ops_t) SetMap_end_fn(arg2 _swig_fnptr) {
	_swig_wrap_llsd_ops_t_map_end_fn_set(arg1, arg2)
}

func _swig_wrap_llsd_ops_t_map_end_fn_get(SwigcptrLlsd_ops_t) _swig_fnptr

func (arg1 SwigcptrLlsd_ops_t) GetMap_end_fn() _swig_fnptr {
	return _swig_wrap_llsd_ops_t_map_end_fn_get(arg1)
}

func _swig_wrap_new_llsd_ops_t() SwigcptrLlsd_ops_t

func NewLlsd_ops_t() Llsd_ops_t {
	return _swig_wrap_new_llsd_ops_t()
}

func _swig_wrap_delete_llsd_ops_t(uintptr)

func DeleteLlsd_ops_t(arg1 Llsd_ops_t) {
	_swig_wrap_delete_llsd_ops_t(arg1.Swigcptr())
}

type Llsd_ops_t interface {
	Swigcptr() uintptr
	SwigIsLlsd_ops_t()
	SetUndef_fn(arg2 _swig_fnptr)
	GetUndef_fn() _swig_fnptr
	SetBoolean_fn(arg2 _swig_fnptr)
	GetBoolean_fn() _swig_fnptr
	SetInteger_fn(arg2 _swig_fnptr)
	GetInteger_fn() _swig_fnptr
	SetReal_fn(arg2 _swig_fnptr)
	GetReal_fn() _swig_fnptr
	SetUuid_fn(arg2 _swig_fnptr)
	GetUuid_fn() _swig_fnptr
	SetString_fn(arg2 _swig_fnptr)
	GetString_fn() _swig_fnptr
	SetDate_fn(arg2 _swig_fnptr)
	GetDate_fn() _swig_fnptr
	SetUri_fn(arg2 _swig_fnptr)
	GetUri_fn() _swig_fnptr
	SetBinary_fn(arg2 _swig_fnptr)
	GetBinary_fn() _swig_fnptr
	SetArray_begin_fn(arg2 _swig_fnptr)
	GetArray_begin_fn() _swig_fnptr
	SetArray_value_begin_fn(arg2 _swig_fnptr)
	GetArray_value_begin_fn() _swig_fnptr
	SetArray_value_end_fn(arg2 _swig_fnptr)
	GetArray_value_end_fn() _swig_fnptr
	SetArray_end_fn(arg2 _swig_fnptr)
	GetArray_end_fn() _swig_fnptr
	SetMap_begin_fn(arg2 _swig_fnptr)
	GetMap_begin_fn() _swig_fnptr
	SetMap_key_begin_fn(arg2 _swig_fnptr)
	GetMap_key_begin_fn() _swig_fnptr
	SetMap_key_end_fn(arg2 _swig_fnptr)
	GetMap_key_end_fn() _swig_fnptr
	SetMap_value_begin_fn(arg2 _swig_fnptr)
	GetMap_value_begin_fn() _swig_fnptr
	SetMap_value_end_fn(arg2 _swig_fnptr)
	GetMap_value_end_fn() _swig_fnptr
	SetMap_end_fn(arg2 _swig_fnptr)
	GetMap_end_fn() _swig_fnptr
}

type Enum_SS_state_e int
func _swig_getTOP_LEVEL() Enum_SS_state_e
var TOP_LEVEL Enum_SS_state_e = _swig_getTOP_LEVEL()
func _swig_getARRAY_BEGIN() Enum_SS_state_e
var ARRAY_BEGIN Enum_SS_state_e = _swig_getARRAY_BEGIN()
func _swig_getARRAY_VALUE_BEGIN() Enum_SS_state_e
var ARRAY_VALUE_BEGIN Enum_SS_state_e = _swig_getARRAY_VALUE_BEGIN()
func _swig_getARRAY_VALUE() Enum_SS_state_e
var ARRAY_VALUE Enum_SS_state_e = _swig_getARRAY_VALUE()
func _swig_getARRAY_VALUE_END() Enum_SS_state_e
var ARRAY_VALUE_END Enum_SS_state_e = _swig_getARRAY_VALUE_END()
func _swig_getARRAY_END() Enum_SS_state_e
var ARRAY_END Enum_SS_state_e = _swig_getARRAY_END()
func _swig_getMAP_BEGIN() Enum_SS_state_e
var MAP_BEGIN Enum_SS_state_e = _swig_getMAP_BEGIN()
func _swig_getMAP_KEY_BEGIN() Enum_SS_state_e
var MAP_KEY_BEGIN Enum_SS_state_e = _swig_getMAP_KEY_BEGIN()
func _swig_getMAP_KEY() Enum_SS_state_e
var MAP_KEY Enum_SS_state_e = _swig_getMAP_KEY()
func _swig_getMAP_KEY_END() Enum_SS_state_e
var MAP_KEY_END Enum_SS_state_e = _swig_getMAP_KEY_END()
func _swig_getMAP_VALUE_BEGIN() Enum_SS_state_e
var MAP_VALUE_BEGIN Enum_SS_state_e = _swig_getMAP_VALUE_BEGIN()
func _swig_getMAP_VALUE() Enum_SS_state_e
var MAP_VALUE Enum_SS_state_e = _swig_getMAP_VALUE()
func _swig_getMAP_VALUE_END() Enum_SS_state_e
var MAP_VALUE_END Enum_SS_state_e = _swig_getMAP_VALUE_END()
func _swig_getMAP_END() Enum_SS_state_e
var MAP_END Enum_SS_state_e = _swig_getMAP_END()
func _swig_wrap_llsd_serialize_to_file(uintptr, uintptr, Enum_SS_llsd_serializer_s, int) int

func Llsd_serialize_to_file(arg1 Struct_SS_llsd_s, arg2 FILE, arg3 Enum_SS_llsd_serializer_s, arg4 int) int {
	return _swig_wrap_llsd_serialize_to_file(arg1.Swigcptr(), arg2.Swigcptr(), arg3, arg4)
}

func _swig_wrap_llsd_parse_from_file(uintptr) SwigcptrStruct_SS_llsd_s

func Llsd_parse_from_file(arg1 FILE) Struct_SS_llsd_s {
	return _swig_wrap_llsd_parse_from_file(arg1.Swigcptr())
}


type SwigcptrInt8_t uintptr
type Int8_t interface {
	Swigcptr() uintptr;
}
func (p SwigcptrInt8_t) Swigcptr() uintptr {
	return uintptr(p)
}

type SwigcptrStruct_SS_llsd_s uintptr
type Struct_SS_llsd_s interface {
	Swigcptr() uintptr;
}
func (p SwigcptrStruct_SS_llsd_s) Swigcptr() uintptr {
	return uintptr(p)
}

type SwigcptrFILE uintptr
type FILE interface {
	Swigcptr() uintptr;
}
func (p SwigcptrFILE) Swigcptr() uintptr {
	return uintptr(p)
}

type SwigcptrInt32_t uintptr
type Int32_t interface {
	Swigcptr() uintptr;
}
func (p SwigcptrInt32_t) Swigcptr() uintptr {
	return uintptr(p)
}

type SwigcptrUint32_t uintptr
type Uint32_t interface {
	Swigcptr() uintptr;
}
func (p SwigcptrUint32_t) Swigcptr() uintptr {
	return uintptr(p)
}

type SwigcptrVoid uintptr
type Void interface {
	Swigcptr() uintptr;
}
func (p SwigcptrVoid) Swigcptr() uintptr {
	return uintptr(p)
}

type SwigcptrList_itr_t uintptr
type List_itr_t interface {
	Swigcptr() uintptr;
}
func (p SwigcptrList_itr_t) Swigcptr() uintptr {
	return uintptr(p)
}

type SwigcptrHt_itr_t uintptr
type Ht_itr_t interface {
	Swigcptr() uintptr;
}
func (p SwigcptrHt_itr_t) Swigcptr() uintptr {
	return uintptr(p)
}

type SwigcptrUint8_t uintptr
type Uint8_t interface {
	Swigcptr() uintptr;
}
func (p SwigcptrUint8_t) Swigcptr() uintptr {
	return uintptr(p)
}

